% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PROBLEM SET LATEX TEMPLATE FILE
% DEFINE DOCUMENT STYLE, LOAD PACKAGES
\documentclass[11pt,notitlepage]{article}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}    % ADD COMMENTS USING A PERCENT SIGN
\usepackage{amsfonts}
\usepackage{amsthm}
\usepackage{amsmath, booktabs}
\usepackage{mathtools}
\usepackage{amssymb}
\usepackage{subfig}
\usepackage{setspace}
\usepackage{fullpage}
\usepackage{verbatim}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{longtable}
\usepackage{multicol}
\usepackage{multirow}
\setlength{\parindent}{0in}  	% uncomment to remove indent at start of paragraphs
\usepackage{pdflscape}
\usepackage[english]{babel}
\usepackage[pdftex]{hyperref}
\usepackage{natbib}
\usepackage{caption}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{graphics}
\usepackage{multirow}
\usepackage{graphics}
\usepackage{hyperref}
\usepackage{longtable}
\usepackage{latexsym}
\usepackage{rotating}
\usepackage{setspace}
\usepackage{layouts} 
\usepackage[titletoc]{appendix}
\DeclareGraphicsExtensions{.pdf,.jpg,.png}
\usepackage[margin=1in]{geometry}
\usepackage{enumerate}
\usepackage{float}

\newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{C}[1]{>{\centering\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{R}[1]{>{\raggedleft\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}

\usepackage[T1]{fontenc}				

\usepackage{xcolor}
\usepackage[printwatermark]{xwatermark}





\title{Field Experiments: Design, Analysis and Interpretation \\
Solutions for Chapter 8 Exercises}
\author{Alan S. Gerber and Donald P. Green\footnote{Solutions prepared by Peter M. Aronow and revised by Alexander Coppock}}
\date{\vspace{-5ex}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

\maketitle

\section*{Question 1}
Important concepts:
\begin{enumerate}[a)]
\item Interpret the expression $Y_i(\mathbf{d}) = Y_i(d)$ and explain how it conveys the non-interference assumption.\\
Answer:\\
The expression $Y_i(d)$ refers to the potential outcome that would be expressed based on the input $d$, which refers to the treatment that subject $i$ receives.  By contrast, $Y_i(\mathbf{d})$ refers to the potential outcome that subject $i$ would express based on the assignments that all of the subjects receive. The equality means that the only input that matters is the treatment that subject $i$ receives. 

\item Why are experiments that involve possible spatial spillover effects (such as the example described in section 8.4) said to involve ``implicit'' clustered assignment?\\
Answer:\\
Because certain units are so closely spaced that if a subject receives spillovers from one of the units, it must receive spillovers from all of the units. In that sense, spillovers are assigned as clusters.

\item In what ways might a within-subjects design violate the non-interference assumption?\\
Answer:\\
In a within-subjects design, the unit of observation is the time period. Non-interference presupposes that each unit's potential outcomes are solely a function of the treatments administered in that period. Possible violations include the following: subjects in one period are affected by the treatments that they may have received in a previous period; subjects in one period may be affected because they anticipate treatments that will be administered in a subsequent period.  

\item What are the attractive properties of a waitlist (or stepped-wedge) design?\\
Answer:\\
If the assumptions for unbiased inference are met, this within-subjects design may provide precise estimates of causal effects even when the number of subjects is limited. In terms of implementation, it may be easier to gain the cooperation of subjects or groups administering the treatment that might otherwise object to the use of a control group because everyone in the study eventually receives the treatment.
\end{enumerate}

\section*{Question 2}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}





\end{verbatim}
\end{kframe}
\end{knitrout}

\section*{Question 3}
Sometimes researchers are reluctant to randomly assign individual students in elementary classrooms because they are concerned that treatments administered to some students are likely to spill over to untreated students in the same classroom. In an attempt to get around possible violations of the non-interference assumption, they assign classrooms as clusters to treatment and control, and administer the treatment to all students in a classroom.
\begin{enumerate}[a)]
\item State the non-interference assumption as it applies to the proposed clustered design. \\
Answer:\\
The non-interference assumption depends on the estimand. If the aim is to estimate the causal effect of the intervention on individual students, the non-interference assumption is the same as usual, namely, that each student's potential outcomes are affected only by the treatment administered to that subject. If one is concerned about transmission of treatments between students in the same classroom, that concern would still apply to a clustered design, since potential outcomes may be affected by the treatments that other subjects in the same classroom receive. On the other hand, if one is interested in classroom-level treatment effects (i.e., the difference between a 100\% treated classroom and a 0\% treated classroom), this design sidesteps concerns about within-classroom interference because they are built into the definition of the estimand. In the latter case, the relevant non-interference assumption holds that classroom outcomes are unaffected by the treatment status of other classrooms (e.g., other classrooms in the same school or grade).
\item What causal estimand does the clustered design identify? Does this causal estimand include or exclude spillovers within classrooms?\\
Answer:\\
The causal estimand identified by the clustered design is the average effect of a classroom being 100\% treated versus 0\% treated. This includes within-classroom spillovers at the individual level, but assumes that across-classroom spillovers do not occur.
\end{enumerate}

\section*{Question 4}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}





\end{verbatim}
\end{kframe}
\end{knitrout}

\section*{Question 5}
In their study of spillover effects, Sinclair, McConnell, and Green sent mailings to ran-domly selected households encouraging them to vote in an upcoming special election.\footnote{Sinclair, McConnell, and Green 2010.} The mailings used a form of ``social pressure,'' disclosing whether the targeted individual had voted in previous elections. Because this type of mail had proven to increase turnout by approximately 4-5 percentage points in previous experiments, Sinclair, McConnell, and Green used it to study whether treatment effects are transmitted across households. Employing a multi-level design, they randomly assigned all, half, or none of the members of each nine-digit zip code to receive mail. For purposes of this example, we focus only on households with one registered voter. The outcome variable is voter turnout as measured by the registrar of voters. The results are as follows. Among registered voters in untreated zip codes, 1,021 of 6,217 cast ballots. Among untreated voters in zip codes where half of the households received mail, 526 of 3,316 registered voters cast ballots. Among treated voters in zip codes where half of the households received mail, 620 of 2,949 voted. Finally, among treated voters in zip codes where every household received mail, turnout was 1,316 of 6,377.
\begin{enumerate}[a)]
\item Using potential outcomes, define the treatment effect of receiving mail addressed to subject $i$.\\
Answer:\\
The definition of personally receiving mail could be defined in three ways (given our focus on one-voter households). It could be (a) the effect of mail on those whose zip code neighbors receive no mail, (b) the effect of mail on those for whom half of the neighboring households in the zip code receive mail, or (c) the effect of mail on those whose zip code neighbors all receive mail. Given the design of this study, only (b) can be estimated empirically because no one receives mail in an untreated zip code, and everyone receives mail in a 100\% treated zip code.

\item Define the ``spillover'' treatment effect of being in a zip code where varying fractions of households are treated.\\
Answer:\\
Holding constant one's own treatment status, one may define three potential outcomes depending on whether none, half, or all of the neighboring households are treated.  When defining the ATE of spillover, one may compare half to none, full to half, or full to none.
\item Propose an estimator for estimating the firsthand and secondhand treatment effects. Show that the estimator is unbiased, explaining the assumptions required to reach this conclusion. \\
Answer:\\
The firsthand effects can be estimated only for those in half-treated zip codes by comparing average outcomes among treated and untreated subjects. One can assess the spillover effect among subjects who receive no mail themselves but reside in either half-treated or untreated zip codes. Similarly, one can assess the spillover effect among subjects who received mail themselves and reside in either 100\% or 50\% treated zip codes. The three assumptions are random assignment (satisfied by design because direct treatments and rates of treatment among neighbors are randomly assigned), non-interference (satisfied if we believe that potential outcomes are solely a function of firsthand treatment and treatment of others in the same zip code; treatment of those outside the zip code is ignored), and excludability (satisfied if we believe that potential outcomes are affected only by firsthand and second hand receipt of mail and not by other factors that might be correlated with treatment assignment).
\item Based on these data, what do you infer about the magnitude of the mailing's direct and indirect effects?\\

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{Z_ind} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlkwd{rep}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{6217}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{3316}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlnum{1}\hlstd{,} \hlnum{2949}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlnum{1}\hlstd{,} \hlnum{6377}\hlstd{))}
\hlstd{Z_zip} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlkwd{rep}\hlstd{(}\hlstr{"none"}\hlstd{,} \hlnum{6217}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlstr{"half"}\hlstd{,} \hlnum{3316}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlstr{"half"}\hlstd{,} \hlnum{2949}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlstr{"all"}\hlstd{,} \hlnum{6377}\hlstd{))}
\hlstd{Y} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlkwd{rep}\hlstd{(}\hlnum{1}\hlstd{,} \hlnum{1021}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{6217}\hlopt{-}\hlnum{1021}\hlstd{),}
       \hlkwd{rep}\hlstd{(}\hlnum{1}\hlstd{,} \hlnum{526}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{3316}\hlopt{-}\hlnum{526}\hlstd{),}
       \hlkwd{rep}\hlstd{(}\hlnum{1}\hlstd{,} \hlnum{620}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{2949}\hlopt{-}\hlnum{620}\hlstd{),}
       \hlkwd{rep}\hlstd{(}\hlnum{1}\hlstd{,} \hlnum{1316}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{6377}\hlopt{-}\hlnum{1316}\hlstd{))}
\hlstd{ate.firsthand.half} \hlkwb{<-}
  \hlkwd{mean}\hlstd{(Y[Z_ind}\hlopt{==}\hlnum{1} \hlopt{&} \hlstd{Z_zip}\hlopt{==}\hlstr{"half"}\hlstd{])} \hlopt{-}
  \hlkwd{mean}\hlstd{(Y[Z_ind}\hlopt{==}\hlnum{0} \hlopt{&} \hlstd{Z_zip}\hlopt{==}\hlstr{"half"}\hlstd{])}
\hlstd{ate.secondhand.untreated} \hlkwb{<-}
  \hlkwd{mean}\hlstd{(Y[Z_ind}\hlopt{==}\hlnum{0} \hlopt{&} \hlstd{Z_zip}\hlopt{==}\hlstr{"half"}\hlstd{])} \hlopt{-}
  \hlkwd{mean}\hlstd{(Y[Z_ind}\hlopt{==}\hlnum{0} \hlopt{&} \hlstd{Z_zip}\hlopt{==}\hlstr{"none"}\hlstd{])}
\hlstd{ate.secondhand.treated} \hlkwb{<-}
  \hlkwd{mean}\hlstd{(Y[Z_ind}\hlopt{==}\hlnum{1} \hlopt{&} \hlstd{Z_zip}\hlopt{==}\hlstr{"all"}\hlstd{])} \hlopt{-}
  \hlkwd{mean}\hlstd{(Y[Z_ind}\hlopt{==}\hlnum{1} \hlopt{&} \hlstd{Z_zip}\hlopt{==}\hlstr{"half"}\hlstd{])}
\hlstd{ate.firsthand.half}
\end{alltt}
\begin{verbatim}
## [1] 0.05161591
\end{verbatim}
\begin{alltt}
\hlstd{ate.secondhand.untreated}
\end{alltt}
\begin{verbatim}
## [1] -0.00560227
\end{verbatim}
\begin{alltt}
\hlstd{ate.secondhand.treated}
\end{alltt}
\begin{verbatim}
## [1] -0.00387413
\end{verbatim}
\end{kframe}
\end{knitrout}

Here, the firsthand effects can be estimated only for those in half-treated zip codes: 620/2949 - 526/3316 = 0.052, or 5.2 percentage points. One can assess spillover effect by way of two different comparisons. In order to assess the effects of spillover among subjects who receive no mail themselves, compare voting rates for those living in 50\% treated zip code to those living in the 0\% treated zip code: 526/3316 - 1021/6217 = -0.006, or negative 0.6 percentage points. In order to assess the effects of spillover among subjects who received mail themselves, compare voting rates for those living in 100\% treated zip codes to those living in 50\% treated zip codes:  1316/6377 - 620/2949 = -0.004, or negative 0.4 percentage points.  Although the estimated firsthand effect is strongly positive, both of the estimated spillover effects are close to zero.
\end{enumerate}

\section*{Question 6}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}





\end{verbatim}
\end{kframe}
\end{knitrout}


\section*{Question 7}
Lab experiments sometimes pair subjects together and have them play against one another in games where each subject is rewarded financially according to the game's outcome. One such game involves making monetary contributions to a public good (e.g., preserving the environment); the game can be arranged such that each player gains financially if both of them make a contribution, but each player is better off still if they contribute nothing while their partner in the game makes a contribution. The treatment is whether the pair of players is allowed to communicate prior to deciding whether to contribute. Suppose that a lab experimenter recruits four subjects and assigns them randomly as pairs to play this game. The outcome is whether each player makes a contribution: $Y_i$ is 1 if the player contributes and 0 otherwise. Each player has three potential outcomes: $Y_{0i}$ is the outcome if players are prevented from communicating, $Y_{1i}$ is the outcome if a player communicates with another player who is ``persuasive,'' and $Y_{2i}$ is the outcome if a player communicates with another player who is ``unpersuasive.'' The table below shows the schedule of potential outcomes for four players, two of whom are persuasive and two of whom are unpersuasive.

% Table generated by Excel2LaTeX from sheet 'Sheet1'
\begin{table}[H]
  \centering
  \caption{Question 7 Table}
    \begin{tabular}{rrrrr}
    \toprule
    Subject  & Type  & $Y_{0i}$   & $Y_{1i}$   & $Y_{2i}$  \\
    \midrule
    1     & Persuasive  & 0     & 1     & 0 \\
    2     & Persuasive  & 1     & 1     & 0 \\
    3     & Unpersuasive  & 0     & 0     & 0 \\
    4     & Unpersuasive  & 1     & 1     & 1 \\
    \bottomrule
    \end{tabular}%
  \label{tab:addlabel}%
\end{table}%

\begin{enumerate}[a)]
\item Calculate the average treatment effect of $Y_{1i} - Y_{0i}$. Calculate the average treatment effect of $Y_{2i} - Y_{0i}$.\\
Answer:\\
The ATE of talking with a persusaive person is (3/4) - (1/2) = (1/4). The ATE of talking with an unpersusaive person is (1/4) - (1/2) = -(1/4). 
\item How many random pairings are possible with four subjects?\\
Answer:\\
There are $4!/(2!(4-2)!) = 6$ pairings.
\item Suppose that the experimenter ignores the distinction between $Y_{1i}$ and $Y_{2i}$ and considers only two treatment conditions: the control condition prevents communication between pairs of players, and the treatment condition allows communication. Call the observed outcomes in the communication condition $Y^{*}_{1i}$. Across all possible random pairings of subjects, what is the average difference-in-means estimate when the average $Y^{*}_{1i}$ is compared to the average $Y_{0i}$ ? Does this number correspond to either of the two estimands defined in part (a)? Does it correspond to the average of these two estimands? \\
Answer:\\
The average difference-in-means estimate is $\frac{0 - 0.5 -1 + 0 + 0.5 + 0.5}{6} = -\frac{1}{12}$. This does not correspond to any of the estimands defined in part a), nor does it correspond to the average of this estimands.

\item What is the probability that a persuasive subject is treated by communicating with an unpersuasive subject? What is the probability that an unpersuasive subject is treated by communicating with an unpersuasive subject? \\
Answer:\\
Subject 1 has a 1/6 chance of being assigned to communicate with a persuasive subject (subject 2) and has a 1/3 chance of being assigned to communicate with an unpersuasive subject (subjects 3 or 4). The same probabilities apply to Subject 2. Subject 3 has a 1/6 chance of communicating with an unpersuasive subject (subject 4).  The same probabilities apply to Subject 4.
\item Briefly summarize why a violation of the non-interference assumption leads to biased difference-in-means estimates in this example. \\
Answer:\\
One's potential outcomes change depending on how the randomization happened to come out. Bias occurs because the probability of encountering a persuasive or unpersuasive partner is related to potential outcomes.

\item Would bias be eliminated if the experimenter replicated this study (with four subjects) each day and averaged the results over a series of 100 daily studies? \\
Answer:\\
It depends. Replicating small experiments with the same combination of persuasive and unpersuasive subjects simply reproduces the bias described above, because each experiment is subject to the same bias.  On the other hand, if one imagines replicating this study with a random draw of the four subject types (see part G below), no bias results because selecting one subject for treatment does not prevent a subject of the same type from being assigned to control.
\item Would bias be eliminated if the experimenter assembled 400 subjects at the same time (imagine 100 subjects for each of the four potential outcomes profiles in the table) and assigned them to pairs? Hint: Answer the question based on the intuition suggested by part (d). \\
Answer:\\
Bias becomes negligible as the size of a given experiment increases, because in a large experiment the probability of encountering a persuasive partner is nearly the same for both persuasive and unpersuasive subjects.
\end{enumerate}

\section*{Question 8}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}





\end{verbatim}
\end{kframe}
\end{knitrout}


\section*{Question 9}
Use data from the hotspots experiment in Table 8.4 (these data are also available at http:// isps.research.yale.edu/FEDAI) and the probabilities that each unit is exposed to immediate or spillover treatments (Table 8.5) to answer the following questions:



\begin{enumerate}[a)]
\item For the subset of 11 hotspot locations that lie outside the range of possible spillovers, calculate $E[Y_{01} - Y_{00}]$, the ATE of immediate police surveillance.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{true_ate} \hlkwb{<-} \hlkwd{with}\hlstd{(hotspots,} \hlkwd{mean}\hlstd{(y01[prox500}\hlopt{==}\hlnum{0}\hlstd{])} \hlopt{-} \hlkwd{mean}\hlstd{(y00[prox500}\hlopt{==}\hlnum{0}\hlstd{]))}
\hlstd{true_ate}
\end{alltt}
\begin{verbatim}
## [1] -5
\end{verbatim}
\begin{alltt}
\hlstd{ate_hat} \hlkwb{<-} \hlkwd{with}\hlstd{(hotspots,} \hlkwd{mean}\hlstd{(y[prox500}\hlopt{==}\hlnum{0} \hlopt{&} \hlstd{assignment}\hlopt{==}\hlnum{1}\hlstd{])} \hlopt{-}
                  \hlkwd{mean}\hlstd{(y00[prox500}\hlopt{==}\hlnum{0} \hlopt{&} \hlstd{assignment}\hlopt{==}\hlnum{0}\hlstd{]))}
\hlstd{ate_hat}
\end{alltt}
\begin{verbatim}
## [1] 3.333333
\end{verbatim}
\end{kframe}
\end{knitrout}
The true ATE for the observations that lie outside the range of possibile spillovers is -5. The estimated ATE using the observed random assignment is 3.33.

\item For the remaining 19 hotspot locations that lie within the range of possible spillovers, calculate $E[Y_{01} - Y_{00}]$, $E[Y_{10} - Y_{00}]$, and $E[Y_{11} - Y_{00}]$.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{true_ate_01} \hlkwb{<-} \hlkwd{with}\hlstd{(hotspots,} \hlkwd{mean}\hlstd{(y01[prox500}\hlopt{==}\hlnum{1}\hlstd{])} \hlopt{-} \hlkwd{mean}\hlstd{(y00[prox500}\hlopt{==}\hlnum{1}\hlstd{]))}
\hlstd{true_ate_10} \hlkwb{<-} \hlkwd{with}\hlstd{(hotspots,} \hlkwd{mean}\hlstd{(y10[prox500}\hlopt{==}\hlnum{1}\hlstd{])} \hlopt{-} \hlkwd{mean}\hlstd{(y00[prox500}\hlopt{==}\hlnum{1}\hlstd{]))}
\hlstd{true_ate_11} \hlkwb{<-} \hlkwd{with}\hlstd{(hotspots,} \hlkwd{mean}\hlstd{(y11[prox500}\hlopt{==}\hlnum{1}\hlstd{])} \hlopt{-} \hlkwd{mean}\hlstd{(y00[prox500}\hlopt{==}\hlnum{1}\hlstd{]))}
\hlstd{true_ate_01}
\end{alltt}
\begin{verbatim}
## [1] -5
\end{verbatim}
\begin{alltt}
\hlstd{true_ate_10}
\end{alltt}
\begin{verbatim}
## [1] 5
\end{verbatim}
\begin{alltt}
\hlstd{true_ate_11}
\end{alltt}
\begin{verbatim}
## [1] -7
\end{verbatim}
\begin{alltt}
\hlstd{hotspots} \hlkwb{<-} \hlkwd{within}\hlstd{(hotspots,\{}
  \hlstd{exposure[exposure} \hlopt{==} \hlnum{11}\hlstd{]} \hlkwb{<-} \hlstr{"11"}  \hlcom{# Indirect and Direct Treatment}
  \hlstd{exposure[exposure} \hlopt{==} \hlnum{10}\hlstd{]} \hlkwb{<-} \hlstr{"10"}  \hlcom{# Indirect Treatment}
  \hlstd{exposure[exposure} \hlopt{==} \hlnum{01}\hlstd{]} \hlkwb{<-} \hlstr{"01"}  \hlcom{# Direct Treatment}
  \hlstd{exposure[exposure} \hlopt{==} \hlnum{00}\hlstd{]} \hlkwb{<-} \hlstr{"00"}  \hlcom{# Control}

  \hlcom{# Calculate probability of assignment to exposure condition}
  \hlstd{Q} \hlkwb{<-} \hlnum{NA}
  \hlstd{Q[exposure} \hlopt{==} \hlstr{"11"}\hlstd{]} \hlkwb{<-} \hlstd{prob11[exposure} \hlopt{==} \hlstr{"11"}\hlstd{]}
  \hlstd{Q[exposure} \hlopt{==} \hlstr{"10"}\hlstd{]} \hlkwb{<-} \hlstd{prob10[exposure} \hlopt{==} \hlstr{"10"}\hlstd{]}
  \hlstd{Q[exposure} \hlopt{==} \hlstr{"01"}\hlstd{]} \hlkwb{<-} \hlstd{prob01[exposure} \hlopt{==} \hlstr{"01"}\hlstd{]}
  \hlstd{Q[exposure} \hlopt{==} \hlstr{"00"}\hlstd{]} \hlkwb{<-} \hlstd{prob00[exposure} \hlopt{==} \hlstr{"00"}\hlstd{]}

  \hlcom{# Generate weights}
  \hlstd{weights} \hlkwb{<-} \hlnum{1}\hlopt{/}\hlstd{Q}
\hlstd{\})}

\hlcom{# Estimate E[Y_\{01\} - Y_\{00\}]:}
\hlstd{fit.01} \hlkwb{<-} \hlkwd{lm}\hlstd{(y} \hlopt{~} \hlstd{exposure,} \hlkwc{weights}\hlstd{=weights,}
             \hlkwd{subset}\hlstd{(hotspots, prox500} \hlopt{>} \hlnum{0} \hlopt{&} \hlstd{exposure} \hlopt{%in%} \hlkwd{c}\hlstd{(}\hlstr{"00"}\hlstd{,} \hlstr{"01"}\hlstd{)))}

\hlcom{# Estimate E[Y_\{10\} - Y_\{00\}]:}
\hlstd{fit.10} \hlkwb{<-} \hlkwd{lm}\hlstd{(y} \hlopt{~} \hlstd{exposure,} \hlkwc{weights}\hlstd{=weights,}
             \hlkwd{subset}\hlstd{(hotspots, prox500} \hlopt{>} \hlnum{0} \hlopt{&} \hlstd{exposure} \hlopt{%in%} \hlkwd{c}\hlstd{(}\hlstr{"00"}\hlstd{,} \hlstr{"10"}\hlstd{)))}

\hlcom{# Estimate E[Y_\{11\} - Y_\{00\}]:}
\hlstd{fit.11} \hlkwb{<-} \hlkwd{lm}\hlstd{(y} \hlopt{~} \hlstd{exposure,} \hlkwc{weights}\hlstd{=weights,}
             \hlkwd{subset}\hlstd{(hotspots, prox500} \hlopt{>} \hlnum{0} \hlopt{&} \hlstd{exposure} \hlopt{%in%} \hlkwd{c}\hlstd{(}\hlstr{"00"}\hlstd{,} \hlstr{"11"}\hlstd{)))}
\end{alltt}
\end{kframe}
\end{knitrout}

Among observations that lie outside the range of possibile spillovers, the ATE of direct treatment is -5, the ate of indirect treatment is 5, and the ATE of direct and indirect treatment together is -7.


% Table created by stargazer v.5.2 by Marek Hlavac, Harvard University. E-mail: hlavac at fas.harvard.edu
% Date and time: Tue, Apr 10, 2018 - 15:37:27
\begin{table}[!htbp] \centering 
  \caption{Question 9c: Treatment Effect Estimates} 
  \label{} 
\begin{tabular}{@{\extracolsep{2pt}}lccc} 
\\[-1.8ex]\hline \\[-1.8ex] 
\\[-1.8ex] & \multicolumn{3}{c}{Crime Rate} \\ 
\\[-1.8ex] & (1) & (2) & (3)\\ 
\hline \\[-1.8ex] 
 exposure01 & $-$16.033 &  &  \\ 
  & (8.065) &  &  \\ 
  exposure10 &  & $-$0.037 &  \\ 
  &  & (9.074) &  \\ 
  exposure11 &  &  & $-$9.606 \\ 
  &  &  & (7.725) \\ 
  Constant & 62.606 & 62.606 & 62.606 \\ 
  & (5.222) & (4.976) & (4.918) \\ 
 N & 12 & 14 & 11 \\ 
R$^{2}$ & 0.283 & 0.00000 & 0.147 \\ 
\hline \\[-1.8ex] 
\multicolumn{4}{l}{} \\ 
\end{tabular} 
\end{table} 


By comparing weighted averages, with weights equal to the inverse of the probability that an observation is assigned to its observed treatment condition, we obtain estimates for the three ATEs: -16.0, -0.04, -9.6, respectively.

\item Use the data at http://isps.research.yale.edu/FEDAI to estimate the average effect of spillover on nonexperimental units. Note that your estimator must make use of the probability that each unit lies within 500 meters of a treated experimental unit; exclude from your analysis any units that have zero probability of experiencing spillovers.



\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{hotspot_nonexp} \hlkwb{<-} \hlkwd{within}\hlstd{(hotspot_nonexp,\{}
  \hlstd{exposure[exposure}\hlopt{==}\hlnum{10}\hlstd{]} \hlkwb{<-} \hlstr{"10"}
  \hlstd{exposure[exposure}\hlopt{==}\hlnum{0}\hlstd{]} \hlkwb{<-} \hlstr{"00"}

  \hlstd{Q} \hlkwb{<-} \hlnum{NA}
  \hlstd{Q[exposure}\hlopt{==}\hlstr{"10"}\hlstd{]} \hlkwb{<-} \hlstd{prob10[exposure}\hlopt{==}\hlstr{"10"}\hlstd{]}
  \hlstd{Q[exposure}\hlopt{==}\hlstr{"00"}\hlstd{]} \hlkwb{<-} \hlstd{prob00[exposure}\hlopt{==}\hlstr{"00"}\hlstd{]}

  \hlstd{weights} \hlkwb{<-} \hlnum{1}\hlopt{/}\hlstd{Q}
  \hlstd{\})}

\hlstd{fit.nonexp} \hlkwb{<-} \hlkwd{lm}\hlstd{(y} \hlopt{~} \hlstd{exposure,} \hlkwc{weights}\hlstd{=weights,}
                 \hlkwc{data}\hlstd{=}\hlkwd{subset}\hlstd{(hotspot_nonexp, prob10} \hlopt{>} \hlnum{0} \hlopt{&} \hlstd{prob10} \hlopt{<} \hlnum{1}\hlstd{))}

\hlstd{fit.nonexp}
\end{alltt}
\begin{verbatim}
## 
## Call:
## lm(formula = y ~ exposure, data = subset(hotspot_nonexp, prob10 > 
##     0 & prob10 < 1), weights = weights)
## 
## Coefficients:
## (Intercept)   exposure10  
##       4.286        4.602
\end{verbatim}
\end{kframe}
\end{knitrout}
 
\end{enumerate}

The estimate of the spillover effects of treatment on the non-experimental units is 4.6.


\section*{Question 10}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}





\end{verbatim}
\end{kframe}
\end{knitrout}

\section*{Question 11}
Return to the stepped-wedge advertising example in section 8.6 and the schedule of assigned treatments in Table 8.8.
\begin{enumerate}[a)]
\item Estimate $E[Y_{01}-Y_{00}]$ by restricting your attention to weeks 2 and 3. How does this estimate compare to the estimate of $E[Y_{11} - Y_{00}]$ presented in the text, which is also identified using observations from weeks 2 and 3?

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# Recreate dataset}
\hlstd{week} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlkwd{rep}\hlstd{(}\hlstr{"2"}\hlstd{,} \hlnum{8}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlstr{"3"}\hlstd{,} \hlnum{8}\hlstd{))}
\hlstd{prob00} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlkwd{rep}\hlstd{(}\hlnum{0.5}\hlstd{,} \hlnum{8}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlnum{0.25}\hlstd{,} \hlnum{8}\hlstd{))}
\hlstd{prob01} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlkwd{rep}\hlstd{(}\hlnum{0.25}\hlstd{,} \hlnum{8}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlnum{0.25}\hlstd{,} \hlnum{8}\hlstd{))}
\hlstd{prob11} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlkwd{rep}\hlstd{(}\hlnum{0.25}\hlstd{,} \hlnum{8}\hlstd{),} \hlkwd{rep}\hlstd{(}\hlnum{0.50}\hlstd{,} \hlnum{8}\hlstd{))}
\hlstd{Y} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlnum{9}\hlstd{,}\hlnum{5}\hlstd{,}\hlnum{2}\hlstd{,}\hlnum{3}\hlstd{,}\hlnum{3}\hlstd{,}\hlnum{8}\hlstd{,}\hlnum{3}\hlstd{,}\hlnum{1}\hlstd{,}
       \hlnum{4}\hlstd{,}\hlnum{7}\hlstd{,}\hlnum{10}\hlstd{,}\hlnum{10}\hlstd{,}\hlnum{3}\hlstd{,}\hlnum{10}\hlstd{,}\hlnum{4}\hlstd{,}\hlnum{3}\hlstd{)}
\hlstd{Z} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlstr{"11"}\hlstd{,} \hlstr{"00"}\hlstd{,} \hlstr{"01"}\hlstd{,} \hlstr{"00"}\hlstd{,} \hlstr{"00"}\hlstd{,} \hlstr{"11"}\hlstd{,} \hlstr{"00"}\hlstd{,} \hlstr{"01"}\hlstd{,}
       \hlstr{"11"}\hlstd{,} \hlstr{"01"}\hlstd{,} \hlstr{"11"}\hlstd{,} \hlstr{"01"}\hlstd{,} \hlstr{"00"}\hlstd{,} \hlstr{"11"}\hlstd{,} \hlstr{"00"}\hlstd{,} \hlstr{"11"}\hlstd{)}

\hlcom{# Estimate E[Y_\{01\}-Y_\{00\}]}
\hlstd{mean01} \hlkwb{<-} \hlkwd{weighted.mean}\hlstd{(Y[Z}\hlopt{==}\hlstr{"01"}\hlstd{],} \hlkwc{w}\hlstd{=}\hlnum{1}\hlopt{/}\hlstd{prob01[Z}\hlopt{==}\hlstr{"01"}\hlstd{])}
\hlstd{mean00} \hlkwb{<-} \hlkwd{weighted.mean}\hlstd{(Y[Z}\hlopt{==}\hlstr{"00"}\hlstd{],} \hlkwc{w}\hlstd{=}\hlnum{1}\hlopt{/}\hlstd{prob01[Z}\hlopt{==}\hlstr{"00"}\hlstd{])}
\hlstd{ate01_00} \hlkwb{<-} \hlstd{mean01} \hlopt{-} \hlstd{mean00}
\hlstd{ate01_00}
\end{alltt}
\begin{verbatim}
## [1] 1.5
\end{verbatim}
\end{kframe}
\end{knitrout}
The effect of immediate treatment appears to be 1.5, which is weaker than the effect mentioned in the text (4.13), possibly suggesting that the effect of immediate treatment is weaker than the effect of immediate and lagged treatment.

\item Estimate $E[Y_{11} - Y_{00}]$ without imposing the assumption that treatment effects disappear after two weeks by restricting your attention to week 2.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# Estimate E[Y_\{11\}-Y_\{00\}]}
\hlstd{mean11} \hlkwb{<-} \hlkwd{weighted.mean}\hlstd{(Y[Z}\hlopt{==}\hlstr{"11"} \hlopt{&} \hlstd{week}\hlopt{==}\hlstr{"2"}\hlstd{],} \hlkwc{w}\hlstd{=}\hlnum{1}\hlopt{/}\hlstd{prob01[Z}\hlopt{==}\hlstr{"01"} \hlopt{&} \hlstd{week}\hlopt{==}\hlstr{"2"}\hlstd{])}
\hlstd{mean00} \hlkwb{<-} \hlkwd{weighted.mean}\hlstd{(Y[Z}\hlopt{==}\hlstr{"00"} \hlopt{&} \hlstd{week}\hlopt{==}\hlstr{"2"}\hlstd{],} \hlkwc{w}\hlstd{=}\hlnum{1}\hlopt{/}\hlstd{prob01[Z}\hlopt{==}\hlstr{"00"} \hlopt{&} \hlstd{week}\hlopt{==}\hlstr{"2"}\hlstd{])}
\hlstd{ate11_00} \hlkwb{<-} \hlstd{mean11} \hlopt{-} \hlstd{mean00}
\hlstd{ate11_00}
\end{alltt}
\begin{verbatim}
## [1] 5
\end{verbatim}
\end{kframe}
\end{knitrout}

Without imposing this assumption and focusing only on week two, the estimated ATE of immediate and lagged treatment is 5.
\end{enumerate}

\end{document}

