% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PROBLEM SET LATEX TEMPLATE FILE
% DEFINE DOCUMENT STYLE, LOAD PACKAGES
\documentclass[11pt,notitlepage]{article}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}    % ADD COMMENTS USING A PERCENT SIGN
\usepackage{amsfonts}
\usepackage{amsthm}
\usepackage{amsmath, booktabs}
\usepackage{mathtools}
\usepackage{amssymb}
\usepackage{subfig}
\usepackage{setspace}
\usepackage{fullpage}
\usepackage{verbatim}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{longtable}
\usepackage{multicol}
\usepackage{multirow}
\setlength{\parindent}{0in}  	% uncomment to remove indent at start of paragraphs
\usepackage{pdflscape}
\usepackage[english]{babel}
\usepackage[pdftex]{hyperref}
\usepackage{natbib}
\usepackage{caption}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{graphics}
\usepackage{multirow}
\usepackage{graphics}
\usepackage{hyperref}
\usepackage{longtable}
\usepackage{latexsym}
\usepackage{rotating}
\usepackage{setspace}
\usepackage{layouts} 
\usepackage[titletoc]{appendix}
\DeclareGraphicsExtensions{.pdf,.jpg,.png}
\usepackage[margin=1in]{geometry}
\usepackage{enumerate}
\usepackage{float}

\newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{C}[1]{>{\centering\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{R}[1]{>{\raggedleft\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
% FONTS
\usepackage[T1]{fontenc}					% always use this no matter what

\usepackage{xcolor}
\usepackage[printwatermark]{xwatermark}


\input{../data/pygments.tex}
% uncomment any one of these to see what it does to your font!
%\usepackage{pxfonts}
%\usepackage{cmbright}
%\usepackage{txfonts}
%\usepackage[adobe-utopia]{mathdesign}
%\usepackage{kpfonts}
%\usepackage{lmodern}
%\usepackage{newtxtext,newtxmath}




% DEFINE WHAT GOES INTO YOUR TITLE BEFORE THE DOCUMENT BEGINS
\title{Field Experiments: Design, Analysis and Interpretation \\
Solutions for Chapter 4 Exercises}
\author{Alan S. Gerber and Donald P. Green\footnote{Solutions prepared by Peter M. Aronow and revised by Alexander Coppock}}
\date{\vspace{-5ex}}

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

\maketitle


\section*{Question 1}
Important concepts: [10pts]

\begin{enumerate}[a)]
\item Define ``covariate.''  Explain why covariates are (at least in principle) measured prior to the random allocation of subjects to treatment and control.\\
Answer:\\
A covariate is a variable that is (1) unaffected by the treatment and (2) used to predict outcomes. In order to increase the credibility of the claim that a given covariate is unaffected by the treatment, researchers typically restrict the set of covariates to those variables that are measured (or are measurable) prior to the random allocation of treatments.

\item Define ``disturbance term.''  \\
Answer:\\
The disturbance term comprises all sources of variation in potential outcomes other than the average treatment effect.  For example, in equation (4.7), the disturbance term is $u_i=Y_i (0)-\mu_{Y(0)}+[(Y_i (1)-\mu_{Y(1)} )-(Y_i (0)-\mu_{Y(0)})] D_i$.  The disturbance term comprises the idiosyncratic variation in untreated responses $Y_i (0)-\mu_{Y(0)}$, plus the idiosyncratic variation in treatment effects $[(Y_i (1)-\mu_{Y(1)})-(Y_i (0)-\mu_{Y(0)})] D_i.$  

\item In equation (4.2), we demonstrated that rescaling the outcome by subtracting a pre-test leads to unbiased estimates of the ATE. Suppose that instead of subtracting the pre-test $X_i$, we subtracted a rescaled pretest $cX_i$, where $c$ is some positive constant.  Show that this procedure produces unbiased estimates of the ATE. \\
Answer:\\
The proof is similar to equation (4.2) and again makes use of the fact that the expected value of $X_i$ is the same in the treatment and control groups when treatments are allocated randomly:

\begin{align*}
E[\widehat{ATE}] &=E[Y_i-cX_i |D_i=1]-E[Y_i-cX_i | D_i=0)]\\
&= E[Y_i|D_i=1]-E[cX_i|D_i=1]-E[Y_i|D_i=0]+E[cX_i|D_i=0]\\
&= E[Y_i|D_i=1]-cE[X_i|D_i=1]-E[Y_i|D_i=0]+cE[X_i|D_i=0]\\
&= E[Y_i(1)] - E[Y_i(0)]
\end{align*}

\item Show that the parameter $b$ in equation (4.7) is identical to the ATE.\\
Answer:\\
Recall from Equation (4.7) that:
\begin{align*}
Y_i & =Y_i (0)(1-D_i )+Y_i (1) D_i\\
&=Y_i (0)+(Y_i (1)-Y_i (0) )D_i\\
&= \mu_{Y(0)}+[\mu_{Y(1)}-\mu_{Y(0)} ] D_i+Y_i (0)-\mu_{Y(0)}+[(Y_i (1)-\mu_{Y(1)} )-(Y_i (0)-\mu_{Y(0)} )] D_i\\
&= a+bD_i+u_i
\end{align*}

This equation implies that $b=\mu_{Y(1)}-\mu_{Y(0)}$, which is the ATE because the expected value of $Y_i (1)$ is $\mu_{Y(1)}$, and the expected value of $Y_i (0)$ is $\mu_{Y(0)}$.

\end{enumerate}

\section*{Question 2}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}






\end{verbatim}
\end{kframe}
\end{knitrout}



\section*{Question 3}
The table below illustrates the problems that may arise when researchers exercise discretion over what results to report to readers. Suppose the true ATE associated with a given treatment were 1.0. The table reports the estimated ATE from nine experiments, each of which involves approximately 200 subjects. Each study produces two estimates, one based on a difference-in-means and another using regression to control for covariates. In principle, both estimators generate unbiased estimates, and covariate adjustment has a slight edge in terms of precision. Suppose the researchers conducting each study use the following decision rule: ``Estimate the ATE using both estimators and report whichever estimate is larger.'' Under this reporting policy, are the reported estimates unbiased? Why or why not? [6 pts]\\
Answer:\\
This procedure leads to biased estimates. Although each estimator is unbiased, the greater of two unbiased estimates is not unbiased. One can think of this procedure as ``Report the no-covariates estimate unless the with-covariates estimate is larger, in which case report the with-covariates estimate.'' On its own, the no-covariates estimate is unbiased, but it tends to be corrected when it generates a lower-than-average estimate. In this example, the average estimate generated by this reporting procedure is 12/9 = 1.33, which is greater than the true ATE of 1.0.

\begin{table}[H]
  \centering
  \caption{Question 3 table}
    \begin{tabular}{r|cc|c}
    \toprule
   \multicolumn{1}{r}{Study} & No covariates & \multicolumn{1}{c}{With covariates} & \multicolumn{1}{c}{Greater of two estimates} \\
    \midrule
    1     & 5     & 4     & 5 \\
    2     & 3     & 3     & 3 \\
    3     & 2     & 2     & 2 \\
    4     & 6     & 5     & 6 \\
    5     & 1     & 1     & 1 \\
    6     & 0     & 0     & 0 \\
    7     & -3    & -1    & -1 \\
    8     & -5    & -4    & -4 \\
    9     & 0     & -1    & 0 \\ \midrule
    Average & 1     & 1     & 1.33 \\
    Standard Deviation & 3.54  & 2.83  & 3.08 \\
    \bottomrule
    \end{tabular}%
  \label{tab:addlabel}%
\end{table}%

\section*{Question 4}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}






\end{verbatim}
\end{kframe}
\end{knitrout}


\section*{Question 5}


Randomizations are said to be ``restricted'' when the set of all possible random allocations is narrowed to exclude allocations that have inadequate covariate balance.  Suppose, for example, that the assignment of treatments ($D_i$) in Table 4.1 was conducted subject to the restriction that a regression of $D_i$ on $X_i$ (the pretest) does not allow the researcher to reject the sharp null hypothesis of no effect of $X_i$ on $D_i$ at the 0.05 significance level) produces a $p$-value on that is greater than 0.05. In other words, had the researcher found that the assigned $D_i$ were significantly predicted by $X_i$, the random allocation would have been conducted again, until the $D_i$ met this criterion. [10pts]

\begin{enumerate}[a)]
\item Conduct a series of random assignments in order to calculate the weighting variable $w_i$; for units in the treatment group, this weight is defined as the inverse of the probability of being assigned to treatment, and for units in the control group, this weight is defined as the inverse of the probability of being assigned to control. See Table 4.2 for an example. Does $w_i$ appear to vary within the treatment group or within the control group?

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}1}]:} \PY{k}{clear}
        \PY{k}{clear}\PY{k}{ matrix}
        \PY{k}{clear}\PY{k}{ mata}
        \PY{k}{set} matsize \PY{l+m}{11000} 
        \PY{k}{set} maxvar \PY{l+m}{32767}
        \PY{k}{set} seed \PY{l+m}{1234567}
        \PY{k}{set}\PY{k}{ more} off
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}2}]:} 
\PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{l}\PY{c+c1}{o}\PY{c+c1}{o}\PY{c+c1}{p}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{o}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{i}\PY{c+c1}{m}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{r}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{o}\PY{c+c1}{m}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{s}\PY{c+c1}{s}\PY{c+c1}{i}\PY{c+c1}{g}\PY{c+c1}{n}\PY{c+c1}{m}\PY{c+c1}{e}\PY{c+c1}{n}\PY{c+c1}{t}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{a}\PY{c+c1}{v}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{o}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{ }\PY{c+c1}{m}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{i}\PY{c+c1}{x}\PY{c+c1}{ }       
        \PY{k}{cap}\PY{k}{ matrix}\PY{k}{ drop} z
        \PY{k}{matrix} z=\PY{n+nf}{J}(\PY{l+m}{40}, \PY{l+m}{10000}, .)
        
        \PY{k}{qui}\PY{k}{ forvalues} i = \PY{l+m}{1}\PY{o}{/}\PY{l+m}{10000} \PYZob{}
        \PY{c+c1}{//}\PY{c+c1}{c}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{a}\PY{c+c1}{v}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{5}\PY{c+c1}{0}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{e}\PY{c+c1}{r}\PY{c+c1}{m}\PY{c+c1}{u}\PY{c+c1}{t}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{i}\PY{c+c1}{o}\PY{c+c1}{n}\PY{c+c1}{s}\PY{c+c1}{ }\PY{c+c1}{o}\PY{c+c1}{f}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{m}\PY{c+c1}{e}\PY{c+c1}{n}\PY{c+c1}{t}
        	import delim 
       \PY{l+s}{\PYZdq{}}\PY{l+s}{.}\PY{l+s}{/}\PY{l+s}{d}\PY{l+s}{a}\PY{l+s}{t}\PY{l+s}{a}\PY{l+s}{/}\PY{l+s}{c}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{p}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{0}\PY{l+s}{4}\PY{l+s}{/}\PY{l+s}{G}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{b}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{G}\PY{l+s}{r}\PY{l+s}{e}\PY{l+s}{e}\PY{l+s}{n}\PY{l+s}{B}\PY{l+s}{o}\PY{l+s}{o}\PY{l+s}{k}\PY{l+s}{\PYZus{}}\PY{l+s}{C}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{p}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{4}\PY{l+s}{\PYZus{}}\PY{l+s}{E}\PY{l+s}{x}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{c}\PY{l+s}{i}\PY{l+s}{s}\PY{l+s}{e}\PY{l+s}{s}\PY{l+s}{\PYZus{}}\PY{l+s}{4}\PY{l+s}{\PYZhy{}}\PY{l+s}{5}\PY{l+s}{.}\PY{l+s}{c}\PY{l+s}{s}\PY{l+s}{v}\PY{l+s}{\PYZdq{}}
        \PY{k}{	tempvar} teststat Z
        \PY{k}{	gen} \PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{\PYZsq{}} = .
        \PY{k}{	gen} \PY{n+nv}{`}\PY{n+nv}{t}\PY{n+nv}{e}\PY{n+nv}{s}\PY{n+nv}{t}\PY{n+nv}{s}\PY{n+nv}{t}\PY{n+nv}{a}\PY{n+nv}{t}\PY{n+nv}{\PYZsq{}} = \PY{o}{\PYZhy{}}\PY{l+m}{1}
        \PY{k}{	while} \PY{n+nv}{`}\PY{n+nv}{t}\PY{n+nv}{e}\PY{n+nv}{s}\PY{n+nv}{t}\PY{n+nv}{s}\PY{n+nv}{t}\PY{n+nv}{a}\PY{n+nv}{t}\PY{n+nv}{\PYZsq{}} \PY{o}{\PYZlt{}} \PY{l+m}{0.05}\PYZob{}
        \PY{k}{		tempvar} rannum Zri t
        \PY{k}{	    gen} \PY{n+nv}{`}\PY{n+nv}{r}\PY{n+nv}{a}\PY{n+nv}{n}\PY{n+nv}{n}\PY{n+nv}{u}\PY{n+nv}{m}\PY{n+nv}{\PYZsq{}}=\PY{n+nf}{uniform}()
        \PY{k}{		egen} \PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{r}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} = cut(\PY{n+nv}{`}\PY{n+nv}{r}\PY{n+nv}{a}\PY{n+nv}{n}\PY{n+nv}{n}\PY{n+nv}{u}\PY{n+nv}{m}\PY{n+nv}{\PYZsq{}}), \PY{n+nf}{group}(\PY{l+m}{2})
        \PY{k}{		qui}\PY{k}{ reg} \PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{r}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} x
        \PY{k}{		gen} \PY{n+nv}{`}\PY{n+nv}{t}\PY{n+nv}{\PYZsq{}} = \PYZus{}b[x]\PY{o}{/}\PYZus{}se[x]		
        \PY{k}{		replace} \PY{n+nv}{`}\PY{n+nv}{t}\PY{n+nv}{e}\PY{n+nv}{s}\PY{n+nv}{t}\PY{n+nv}{s}\PY{n+nv}{t}\PY{n+nv}{a}\PY{n+nv}{t}\PY{n+nv}{\PYZsq{}} = \PY{l+m}{2}\PY{o}{*}\PY{n+nf}{ttail}(\PY{n+nf}{e}(df\PYZus{}r),\PY{n+nf}{abs}(\PY{n+nv}{`}\PY{n+nv}{t}\PY{n+nv}{\PYZsq{}}))	
        	\PYZcb{}
        \PY{k}{	replace} \PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{\PYZsq{}} = \PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{r}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}
        \PY{k}{	forvalues} j = \PY{l+m}{1}\PY{o}{/}\PY{l+m}{40} \PYZob{}
        \PY{k}{	matrix} z[\PY{n+nv}{`}\PY{n+nv}{j}\PY{n+nv}{\PYZsq{}}, \PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}] = \PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{\PYZsq{}}[\PY{n+nv}{`}\PY{n+nv}{j}\PY{n+nv}{\PYZsq{}}]
        	\PYZcb{}
        \PY{k}{	drop} \PYZus{}all
        \PYZcb{}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}3}]:} \PY{k}{qui} import delim 
	\PY{l+s}{\PYZdq{}}\PY{l+s}{.}\PY{l+s}{/}\PY{l+s}{d}\PY{l+s}{a}\PY{l+s}{t}\PY{l+s}{a}\PY{l+s}{/}\PY{l+s}{c}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{p}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{0}\PY{l+s}{4}\PY{l+s}{/}\PY{l+s}{G}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{b}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{G}\PY{l+s}{r}\PY{l+s}{e}\PY{l+s}{e}\PY{l+s}{n}\PY{l+s}{B}\PY{l+s}{o}\PY{l+s}{o}\PY{l+s}{k}\PY{l+s}{\PYZus{}}\PY{l+s}{C}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{p}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{4}\PY{l+s}{\PYZus{}}\PY{l+s}{E}\PY{l+s}{x}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{c}\PY{l+s}{i}\PY{l+s}{s}\PY{l+s}{e}\PY{l+s}{s}\PY{l+s}{\PYZus{}}\PY{l+s}{4}\PY{l+s}{\PYZhy{}}\PY{l+s}{5}\PY{l+s}{.}\PY{l+s}{c}\PY{l+s}{s}\PY{l+s}{v}\PY{l+s}{\PYZdq{}},\PY{k}{ clear}
        \PY{k}{rename}\PY{k}{ d} D
        \PY{k}{rename} y Y
        \PY{k}{matrix} rowm = z \PY{o}{*} \PY{n+nf}{J}(\PY{n+nf}{colsof}(z), \PY{l+m}{1}, \PY{l+m}{1}\PY{o}{/}\PY{n+nf}{colsof}(z))
        \PY{k}{matrix} colnames rowm=probs
        \PY{k}{svmat} double rowm, names(col)       
        \PY{k}{qui}\PY{k}{ gen} weights = (\PY{l+m}{1}\PY{o}{/}probs)\PY{o}{*}D \PY{o}{+}(\PY{l+m}{1}\PY{o}{/}(\PY{l+m}{1}\PY{o}{\PYZhy{}}probs))\PY{o}{*}(\PY{l+m}{1}\PY{o}{\PYZhy{}}D)        
        \PY{k}{tabstat} weights,\PY{k}{ by}(D) stat(v)
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
Summary for variables: weights
     by categories of: D (D)

       D |  variance
---------+----------
       0 |  .0004185
       1 |   .000625
---------+----------
   Total |  .0005084
--------------------

    \end{Verbatim}
\end{kframe}
\end{knitrout}

The variance of the weights is \ensuremath{4\times 10^{-4}} in the treatment condition and \ensuremath{6\times 10^{-4}} in the control condition. Indeed, units do have different probabilities of assignments as a result of the restriction scheme, but the differences are small.

\item Use randomization inference to test the sharp null hypothesis that $D_i$ has no effect on $Y_i$ by regressing $Y_i$ on $D_i$ and comparing the estimate to the sampling distribution under the null hypothesis. Make sure that your sampling distribution includes only random allocations that satisfy the restriction mentioned above. Be sure to weight units by inverse probability weights as produced by the random allocation procedure. Estimate the ATE, calculate the $p$-value, and interpret the results.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}4}]:} \PY{k}{qui}\PY{k}{ reg} Y D [pw=weights]
        \PY{k}{global} ate\PYZus{}restricted\PYZus{}RA = \PYZus{}b[D]
        
        \PY{k}{di} \PY{l+s}{\PYZdq{}}\PY{l+s}{A}\PY{l+s}{T}\PY{l+s}{E}\PY{l+s}{ }\PY{l+s}{(}\PY{l+s}{R}\PY{l+s}{e}\PY{l+s}{s}\PY{l+s}{t}\PY{l+s}{r}\PY{l+s}{i}\PY{l+s}{c}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{d}\PY{l+s}{ }\PY{l+s}{A}\PY{l+s}{s}\PY{l+s}{s}\PY{l+s}{i}\PY{l+s}{g}\PY{l+s}{n}\PY{l+s}{m}\PY{l+s}{e}\PY{l+s}{n}\PY{l+s}{t}\PY{l+s}{)}\PY{l+s}{=}\PY{l+s}{ }\PY{l+s}{\PYZdq{}} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}restricted\PYZus{}RA}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
ATE (Restricted Assignment)= 10.712532
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}5}]:} \PY{k}{svmat} z
        
        \PY{k}{cap}\PY{k}{ matrix}\PY{k}{ drop} y\PYZus{}dis
        \PY{k}{matrix} y\PYZus{}dis=\PY{n+nf}{J}(\PY{l+m}{10000}, \PY{l+m}{1}, .)
        
        \PY{k}{forvalues} i = \PY{l+m}{1}\PY{o}{/}\PY{l+m}{10000} \PYZob{}
        \PY{k}{	tempvar} weight\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}
        \PY{k}{	gen} \PY{n+nv}{`}\PY{n+nv}{w}\PY{n+nv}{e}\PY{n+nv}{i}\PY{n+nv}{g}\PY{n+nv}{h}\PY{n+nv}{t}\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}\PY{n+nv}{\PYZsq{}} = (\PY{l+m}{1}\PY{o}{/}probs)\PY{o}{*}z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} \PY{o}{+}(\PY{l+m}{1}\PY{o}{/}(\PY{l+m}{1}\PY{o}{\PYZhy{}}probs))\PY{o}{*}(\PY{l+m}{1}\PY{o}{\PYZhy{}}z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}})
        \PY{k}{	qui}\PY{k}{ reg} Y z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} [pw=\PY{n+nv}{`}\PY{n+nv}{w}\PY{n+nv}{e}\PY{n+nv}{i}\PY{n+nv}{g}\PY{n+nv}{h}\PY{n+nv}{t}\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}\PY{n+nv}{\PYZsq{}}]
        \PY{k}{	matrix} y\PYZus{}dis[\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}, \PY{l+m}{1}] = \PYZus{}b[z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}]
        
        \PYZcb{}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}6}]:} \PY{k}{preserve}
         \PY{k}{svmat} y\PYZus{}dis      
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{ }\PY{c+c1}{v}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{u}\PY{c+c1}{e}
         \PY{k}{count}\PY{k}{ if} \PY{n+nf}{abs}(y\PYZus{}dis1) \PY{o}{\PYZgt{}} \PY{n+nf}{abs}(\PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}restricted\PYZus{}RA})
         \PY{k}{di} \PY{n+nf}{r}(N)\PY{o}{/}\PYZus{}N
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
  56

.0056
    \end{Verbatim}
\end{kframe}
\end{knitrout}


The IPW estimate of the ATE is 10.71, which is close to the unweighted estimate above.  Using a two-tailed test in order to evaluate the null hypothesis that the treatment has no effect for any subject, we find a p-value of 0.0056, which leads us to reject the null hypothesis in favor of the alternative hypothesis that the treatment has some effect. 

\item Use randomization inference to test the sharp null hypothesis that $D_i$ has no effect on $Y_i$ by regressing $Y_i$ on $D_i$ and $X_i$ and comparing the estimate to the sampling distribution under the null hypothesis.  Estimate the ATE, calculate the $p$-value, and interpret the results. 


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}7}]:} \PY{k}{qui}\PY{k}{ reg} Y x D [pw=weights]
         \PY{k}{global} ate\PYZus{}cov\PYZus{}restricted\PYZus{}RA = \PYZus{}b[D]
         \PY{k}{di} \PY{l+s}{\PYZdq{}}\PY{l+s}{A}\PY{l+s}{T}\PY{l+s}{E}\PY{l+s}{ }\PY{l+s}{C}\PY{l+s}{o}\PY{l+s}{n}\PY{l+s}{t}\PY{l+s}{r}\PY{l+s}{o}\PY{l+s}{l}\PY{l+s}{l}\PY{l+s}{i}\PY{l+s}{n}\PY{l+s}{g}\PY{l+s}{ }\PY{l+s}{C}\PY{l+s}{o}\PY{l+s}{v}\PY{l+s}{a}\PY{l+s}{r}\PY{l+s}{i}\PY{l+s}{a}\PY{l+s}{n}\PY{l+s}{c}\PY{l+s}{e}\PY{l+s}{ }\PY{l+s}{(}\PY{l+s}{R}\PY{l+s}{e}\PY{l+s}{s}\PY{l+s}{t}\PY{l+s}{r}\PY{l+s}{i}\PY{l+s}{c}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{d}\PY{l+s}{ }\PY{l+s}{A}\PY{l+s}{s}\PY{l+s}{s}\PY{l+s}{i}\PY{l+s}{g}\PY{l+s}{n}\PY{l+s}{m}\PY{l+s}{e}\PY{l+s}{n}\PY{l+s}{t}\PY{l+s}{)}\PY{l+s}{=}\PY{l+s}{ }\PY{l+s}{\PYZdq{}} 
        		 \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}cov\PYZus{}restricted\PYZus{}RA}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
ATE Controlling Covariance (Restricted Assignment)= 5.3186105
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}8}]:} \PY{k}{cap}\PY{k}{ matrix}\PY{k}{ drop} cov\PYZus{}dis
         \PY{k}{matrix} cov\PYZus{}dis=\PY{n+nf}{J}(\PY{l+m}{10000}, \PY{l+m}{1}, .)        
         \PY{k}{forvalues} i = \PY{l+m}{1}\PY{o}{/}\PY{l+m}{10000}\PYZob{}
         \PY{k}{		tempvar} weight\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}
         \PY{k}{		gen} \PY{n+nv}{`}\PY{n+nv}{w}\PY{n+nv}{e}\PY{n+nv}{i}\PY{n+nv}{g}\PY{n+nv}{h}\PY{n+nv}{t}\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}\PY{n+nv}{\PYZsq{}} = (\PY{l+m}{1}\PY{o}{/}probs)\PY{o}{*}z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} \PY{o}{+}(\PY{l+m}{1}\PY{o}{/}(\PY{l+m}{1}\PY{o}{\PYZhy{}}probs))\PY{o}{*}(\PY{l+m}{1}\PY{o}{\PYZhy{}}z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}})
         \PY{k}{		qui}\PY{k}{ reg} Y x z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} [pw=\PY{n+nv}{`}\PY{n+nv}{w}\PY{n+nv}{e}\PY{n+nv}{i}\PY{n+nv}{g}\PY{n+nv}{h}\PY{n+nv}{t}\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}\PY{n+nv}{\PYZsq{}}]		
         \PY{k}{		matrix} cov\PYZus{}dis[\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}, \PY{l+m}{1}] = \PYZus{}b[z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}]
         
         \PYZcb{}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}9}]:} \PY{k}{preserve}
         \PY{k}{svmat} cov\PYZus{}dis
         
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{.}\PY{c+c1}{v}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{u}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{n}\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{o}\PY{c+c1}{l}\PY{c+c1}{l}\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{g}\PY{c+c1}{ }\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{v}\PY{c+c1}{a}\PY{c+c1}{r}\PY{c+c1}{i}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{c}\PY{c+c1}{e}
         \PY{k}{count}\PY{k}{ if} \PY{n+nf}{abs}(cov\PYZus{}dis1) \PY{o}{\PYZgt{}} \PY{n+nf}{abs}(\PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}cov\PYZus{}restricted\PYZus{}RA})
         \PY{k}{di} \PY{n+nf}{r}(N)\PY{o}{/}\PYZus{}N
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
  28

.0028
    \end{Verbatim}

\end{kframe}
\end{knitrout}

The IPW estimate of the ATE is 5.32, which is close to the unweighted estimate above. We again use a two-tailed test in order to evaluate the null hypothesis that the treatment has no effect for any subject. We find a $p$-value of 0.0028, which leads us to reject the null hypothesis in favor of the alternative hypothesis that the treatment has some effect.

\item Compare the sampling distributions under the null hypothesis in parts (a) and (b) to the sampling distributions obtained in exercises 4(d) and 4(e), which assumed that the randomization was unrestricted.  

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}10}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{s}\PY{c+cm}{e}\PY{c+cm}{\PYZus{}}\PY{c+cm}{c}\PY{c+cm}{o}\PY{c+cm}{m}\PY{c+cm}{p}\PY{c+cm}{l}\PY{c+cm}{e}\PY{c+cm}{t}\PY{c+cm}{e}\PY{c+cm}{\PYZus{}}\PY{c+cm}{R}\PY{c+cm}{A}
         
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{c}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{c}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{m}\PY{c+c1}{p}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{R}\PY{c+c1}{A}
         \PY{k}{qui}\PY{k}{ reg} Y D
         \PY{k}{global} ate\PYZus{}complete\PYZus{}RA = \PYZus{}b[D]
         \PY{k}{di} \PY{l+s}{\PYZdq{}}\PY{l+s}{A}\PY{l+s}{T}\PY{l+s}{E}\PY{l+s}{ }\PY{l+s}{u}\PY{l+s}{n}\PY{l+s}{d}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{ }\PY{l+s}{C}\PY{l+s}{o}\PY{l+s}{m}\PY{l+s}{p}\PY{l+s}{l}\PY{l+s}{e}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{ }\PY{l+s}{A}\PY{l+s}{s}\PY{l+s}{s}\PY{l+s}{i}\PY{l+s}{g}\PY{l+s}{n}\PY{l+s}{m}\PY{l+s}{e}\PY{l+s}{n}\PY{l+s}{t}\PY{l+s}{ }\PY{l+s}{=}\PY{l+s}{ }\PY{l+s}{\PYZdq{}} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}complete\PYZus{}RA}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
ATE under Complete Assignment = 10.7
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}11}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{R}\PY{c+c1}{I}\PY{c+c1}{ }\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{e}\PY{c+c1}{r}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{h}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{n}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{l}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{=}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{m}\PY{c+c1}{p}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{R}\PY{c+c1}{A}
         \PY{k}{cap}\PY{k}{ drop} Y0\PYZus{}sim Y1\PYZus{}sim Y\PYZus{}sim
         \PY{k}{qui}\PY{k}{ gen} Y0\PYZus{}sim = Y
         \PY{k}{qui}\PY{k}{ gen} Y1\PYZus{}sim = Y
         \PY{k}{qui}\PY{k}{ gen} Y\PYZus{}sim = .
         \PY{k}{qui}\PY{k}{ replace} Y0\PYZus{}sim = Y \PY{o}{\PYZhy{}} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}complete\PYZus{}RA}\PY{k}{ if} D\PY{o}{==}\PY{l+m}{1}
         \PY{k}{qui}\PY{k}{ replace} Y1\PYZus{}sim = Y \PY{o}{+} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}complete\PYZus{}RA}\PY{k}{ if} D\PY{o}{==}\PY{l+m}{0}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}12}]:} \PY{k}{capture}\PY{k}{ program}\PY{k}{ drop} ate\PYZus{}complete\PYZus{}RA\PYZus{}ri
         \PY{k}{program} define ate\PYZus{}complete\PYZus{}RA\PYZus{}ri, rclass
         \PY{k}{	replace} Y\PYZus{}sim = Y0\PYZus{}sim\PY{o}{*}(\PY{l+m}{1}\PY{o}{\PYZhy{}}D) \PY{o}{+} Y1\PYZus{}sim\PY{o}{*}(D) 
         \PY{k}{	regress} Y\PYZus{}sim D 
         \PY{k}{    return}\PY{k}{ scalar} Ys\PYZus{}complete\PYZus{}RA=\PYZus{}b[D]	
         end
         
         tsrtest D \PY{n+nf}{r}(Ys\PYZus{}complete\PYZus{}RA) using distout\PYZus{}complete\PYZus{}RA\PY{l+m}{.}dta, \PY{c+cs}{///}
         overwrite: ate\PYZus{}complete\PYZus{}RA\PYZus{}ri
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
Two-sample randomization test for 
theta=r(Ys\_complete\_RA) of ate\_complete\_RA\_ri by D

Combinations:   137846528820 = (40 choose 20)
Assuming null=0
Observed theta: 10.7

Minimum time needed for exact test (h:m:s):  392479:42:00
Reverting to Monte Carlo simulation.
Mode: simulation (10000 repetitions)

progress: |{\ldots}|

 p=0.48995 [one-tailed test of Ho:  theta(D==0)<=theta(D==1)]
 p=0.50995 [one-tailed test of Ho:  theta(D==0)>=theta(D==1)]
 p=0.48995 [two-tailed test of Ho:  theta(D==0)==theta(D==1)]

Saving log file to distout\_complete\_RA.dta{\ldots}done.

    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}13}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{c}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{c}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{m}\PY{c+c1}{p}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{R}\PY{c+c1}{A}
         \PY{k}{preserve}
         \PY{k}{use} \PY{l+s}{\PYZdq{}}\PY{l+s}{d}\PY{l+s}{i}\PY{l+s}{s}\PY{l+s}{t}\PY{l+s}{o}\PY{l+s}{u}\PY{l+s}{t}\PY{l+s}{\PYZus{}}\PY{l+s}{c}\PY{l+s}{o}\PY{l+s}{m}\PY{l+s}{p}\PY{l+s}{l}\PY{l+s}{e}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{\PYZus{}}\PY{l+s}{R}\PY{l+s}{A}\PY{l+s}{.}\PY{l+s}{d}\PY{l+s}{t}\PY{l+s}{a}\PY{l+s}{\PYZdq{}},\PY{k}{ clear}
         \PY{k}{qui}\PY{k}{ drop}\PY{k}{ if} \PYZus{}n\PY{o}{==}\PY{l+m}{1}
         \PY{k}{tabstat} theta, stat(sd)
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
    variable |        sd
-------------+----------
       theta |  4.673591
------------------------


    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}14}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{s}\PY{c+cm}{e}\PY{c+cm}{\PYZus{}}\PY{c+cm}{c}\PY{c+cm}{o}\PY{c+cm}{v}\PY{c+cm}{\PYZus{}}\PY{c+cm}{c}\PY{c+cm}{o}\PY{c+cm}{m}\PY{c+cm}{p}\PY{c+cm}{l}\PY{c+cm}{e}\PY{c+cm}{t}\PY{c+cm}{e}\PY{c+cm}{\PYZus{}}\PY{c+cm}{R}\PY{c+cm}{A}
         
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{c}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{c}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{v}\PY{c+c1}{\PYZus{}}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{m}\PY{c+c1}{p}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{R}\PY{c+c1}{A}
         \PY{k}{qui}\PY{k}{ reg} Y D x
         \PY{k}{global} ate\PYZus{}cov\PYZus{}complete\PYZus{}RA = \PYZus{}b[D]
         \PY{k}{di} \PY{l+s}{\PYZdq{}}\PY{l+s}{A}\PY{l+s}{T}\PY{l+s}{E}\PY{l+s}{ }\PY{l+s}{C}\PY{l+s}{o}\PY{l+s}{n}\PY{l+s}{t}\PY{l+s}{r}\PY{l+s}{o}\PY{l+s}{l}\PY{l+s}{l}\PY{l+s}{i}\PY{l+s}{n}\PY{l+s}{g}\PY{l+s}{ }\PY{l+s}{C}\PY{l+s}{o}\PY{l+s}{v}\PY{l+s}{a}\PY{l+s}{r}\PY{l+s}{i}\PY{l+s}{a}\PY{l+s}{n}\PY{l+s}{c}\PY{l+s}{e}\PY{l+s}{ }\PY{l+s}{u}\PY{l+s}{n}\PY{l+s}{d}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{ }\PY{l+s}{C}\PY{l+s}{o}\PY{l+s}{m}\PY{l+s}{p}\PY{l+s}{l}\PY{l+s}{e}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{ }\PY{l+s}{A}\PY{l+s}{s}\PY{l+s}{s}\PY{l+s}{i}\PY{l+s}{g}\PY{l+s}{n}\PY{l+s}{m}\PY{l+s}{e}\PY{l+s}{n}\PY{l+s}{t}\PY{l+s}{=}\PY{l+s}{ }\PY{l+s}{\PYZdq{}} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}cov\PYZus{}complete\PYZus{}RA}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
ATE Controlling Covariance under Complete Assignment= 5.3155362
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}15}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{R}\PY{c+c1}{I}\PY{c+c1}{ }\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{e}\PY{c+c1}{r}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{h}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{n}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{l}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{=}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{v}\PY{c+c1}{\PYZus{}}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{m}\PY{c+c1}{p}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{R}\PY{c+c1}{A}
         \PY{k}{cap}\PY{k}{ drop} Y0\PYZus{}sim Y1\PYZus{}sim Y\PYZus{}sim
         \PY{k}{qui}\PY{k}{ gen} Y0\PYZus{}sim = Y
         \PY{k}{qui}\PY{k}{ gen} Y1\PYZus{}sim = Y
         \PY{k}{qui}\PY{k}{ gen} Y\PYZus{}sim = .
         \PY{k}{qui}\PY{k}{ replace} Y0\PYZus{}sim = Y \PY{o}{\PYZhy{}} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}cov\PYZus{}complete\PYZus{}RA}\PY{k}{ if} D\PY{o}{==}\PY{l+m}{1}
         \PY{k}{qui}\PY{k}{ replace} Y1\PYZus{}sim = Y \PY{o}{+} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}cov\PYZus{}complete\PYZus{}RA}\PY{k}{ if} D\PY{o}{==}\PY{l+m}{0}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}16}]:} \PY{k}{capture}\PY{k}{ program}\PY{k}{ drop} ate\PYZus{}cov\PYZus{}complete\PYZus{}RA\PYZus{}ri
         \PY{k}{program} define ate\PYZus{}cov\PYZus{}complete\PYZus{}RA\PYZus{}ri, rclass
         \PY{k}{	replace} Y\PYZus{}sim = Y0\PYZus{}sim\PY{o}{*}(\PY{l+m}{1}\PY{o}{\PYZhy{}}D) \PY{o}{+} Y1\PYZus{}sim\PY{o}{*}(D) 
         \PY{k}{	regress} Y\PYZus{}sim D x
         \PY{k}{    return}\PY{k}{ scalar} Ys\PYZus{}cov\PYZus{}complete\PYZus{}RA=\PYZus{}b[D]	
         end
         
         tsrtest D \PY{n+nf}{r}(Ys\PYZus{}cov\PYZus{}complete\PYZus{}RA) using distout\PYZus{}cov\PYZus{}complete\PYZus{}RA\PY{l+m}{.}dta, \PY{c+cs}{///}
         overwrite: ate\PYZus{}cov\PYZus{}complete\PYZus{}RA\PYZus{}ri
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
Two-sample randomization test for 
theta=r(Ys\_cov\_complete\_RA) of ate\_cov\_complete\_RA\_ri by D

Combinations:   137846528820 = (40 choose 20)
Assuming null=0
Observed theta: 5.316

Minimum time needed for exact test (h:m:s):  408561:47:43
Reverting to Monte Carlo simulation.
Mode: simulation (10000 repetitions)

progress: |{\ldots}|

 p=0.50495 [one-tailed test of Ho:  theta(D==0)<=theta(D==1)]
 p=0.49495 [one-tailed test of Ho:  theta(D==0)>=theta(D==1)]
 p=0.50495 [two-tailed test of Ho:  theta(D==0)==theta(D==1)]

Saving log file to distout\_cov\_complete\_RA.dta{\ldots}done.

    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}17}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{c}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{c}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{v}\PY{c+c1}{\PYZus{}}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{m}\PY{c+c1}{p}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{R}\PY{c+c1}{A}
         \PY{k}{preserve}
         \PY{k}{use} \PY{l+s}{\PYZdq{}}\PY{l+s}{d}\PY{l+s}{i}\PY{l+s}{s}\PY{l+s}{t}\PY{l+s}{o}\PY{l+s}{u}\PY{l+s}{t}\PY{l+s}{\PYZus{}}\PY{l+s}{c}\PY{l+s}{o}\PY{l+s}{v}\PY{l+s}{\PYZus{}}\PY{l+s}{c}\PY{l+s}{o}\PY{l+s}{m}\PY{l+s}{p}\PY{l+s}{l}\PY{l+s}{e}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{\PYZus{}}\PY{l+s}{R}\PY{l+s}{A}\PY{l+s}{.}\PY{l+s}{d}\PY{l+s}{t}\PY{l+s}{a}\PY{l+s}{\PYZdq{}},\PY{k}{ clear}
         \PY{k}{qui}\PY{k}{ drop}\PY{k}{ if} \PYZus{}n\PY{o}{==}\PY{l+m}{1}
         \PY{k}{tabstat} theta, stat(sd)
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]

    variable |        sd
-------------+----------
       theta |  1.577595
------------------------

    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}18}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{s}\PY{c+cm}{e}\PY{c+cm}{\PYZus{}}\PY{c+cm}{r}\PY{c+cm}{e}\PY{c+cm}{s}\PY{c+cm}{t}\PY{c+cm}{r}\PY{c+cm}{i}\PY{c+cm}{c}\PY{c+cm}{t}\PY{c+cm}{e}\PY{c+cm}{d}\PY{c+cm}{\PYZus{}}\PY{c+cm}{R}\PY{c+cm}{A}

         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{c}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{c}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{i}\PY{c+c1}{c}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{d}\PY{c+c1}{\PYZus{}}\PY{c+c1}{R}\PY{c+c1}{A}
         \PY{k}{di} \PY{l+s}{\PYZdq{}}\PY{l+s}{A}\PY{l+s}{T}\PY{l+s}{E}\PY{l+s}{ }\PY{l+s}{u}\PY{l+s}{n}\PY{l+s}{d}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{ }\PY{l+s}{R}\PY{l+s}{e}\PY{l+s}{s}\PY{l+s}{t}\PY{l+s}{r}\PY{l+s}{i}\PY{l+s}{c}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{d}\PY{l+s}{ }\PY{l+s}{A}\PY{l+s}{s}\PY{l+s}{s}\PY{l+s}{i}\PY{l+s}{g}\PY{l+s}{n}\PY{l+s}{m}\PY{l+s}{e}\PY{l+s}{n}\PY{l+s}{t}\PY{l+s}{=}\PY{l+s}{ }\PY{l+s}{\PYZdq{}} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}restricted\PYZus{}RA}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
ATE under Restricted Assignment= 10.712532
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}19}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{R}\PY{c+c1}{I}\PY{c+c1}{ }\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{e}\PY{c+c1}{r}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{h}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{n}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{l}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{=}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{i}\PY{c+c1}{c}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{d}\PY{c+c1}{\PYZus{}}\PY{c+c1}{R}\PY{c+c1}{A}
         \PY{k}{cap}\PY{k}{ drop} Y0\PYZus{}sim Y1\PYZus{}sim Y\PYZus{}sim
         \PY{k}{qui}\PY{k}{ gen} Y0\PYZus{}sim = Y
         \PY{k}{qui}\PY{k}{ gen} Y1\PYZus{}sim = Y
         \PY{k}{qui}\PY{k}{ gen} Y\PYZus{}sim = .
         \PY{k}{qui}\PY{k}{ replace} Y0\PYZus{}sim = Y \PY{o}{\PYZhy{}} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}restricted\PYZus{}RA}\PY{k}{ if} D\PY{o}{==}\PY{l+m}{1}
         \PY{k}{qui}\PY{k}{ replace} Y1\PYZus{}sim = Y \PY{o}{+} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}restricted\PYZus{}RA}\PY{k}{ if} D\PY{o}{==}\PY{l+m}{0}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}20}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{c}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{p}\PY{c+c1}{a}\PY{c+c1}{c}\PY{c+c1}{e}
         \PY{k}{drop} \PYZus{}\PYZus{}00\PY{o}{*}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}21}]:} \PY{k}{cap}\PY{k}{ matrix}\PY{k}{ drop} distout\PYZus{}restricted\PYZus{}RA
         \PY{k}{matrix} distout\PYZus{}restricted\PYZus{}RA=\PY{n+nf}{J}(\PY{l+m}{10000}, \PY{l+m}{1}, .)
         
         \PY{k}{qui}\PY{k}{ forvalues} i = \PY{l+m}{1}\PY{o}{/}\PY{l+m}{10000} \PYZob{}
         \PY{k}{	tempvar} weight\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}
         \PY{k}{	gen} \PY{n+nv}{`}\PY{n+nv}{w}\PY{n+nv}{e}\PY{n+nv}{i}\PY{n+nv}{g}\PY{n+nv}{h}\PY{n+nv}{t}\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}\PY{n+nv}{\PYZsq{}} = (\PY{l+m}{1}\PY{o}{/}probs)\PY{o}{*}z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} \PY{o}{+}(\PY{l+m}{1}\PY{o}{/}(\PY{l+m}{1}\PY{o}{\PYZhy{}}probs))\PY{o}{*}(\PY{l+m}{1}\PY{o}{\PYZhy{}}z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}})
         \PY{k}{	replace} Y\PYZus{}sim = Y0\PYZus{}sim\PY{o}{*}(\PY{l+m}{1}\PY{o}{\PYZhy{}}z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}) \PY{o}{+} Y1\PYZus{}sim\PY{o}{*}(z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}})
         \PY{k}{	qui}\PY{k}{ reg} Y\PYZus{}sim z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} [pw=\PY{n+nv}{`}\PY{n+nv}{w}\PY{n+nv}{e}\PY{n+nv}{i}\PY{n+nv}{g}\PY{n+nv}{h}\PY{n+nv}{t}\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}\PY{n+nv}{\PYZsq{}}]
         \PY{k}{	matrix} distout\PYZus{}restricted\PYZus{}RA[\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}, \PY{l+m}{1}] = \PYZus{}b[z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}]
         
         \PYZcb{}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}22}]:} \PY{c+cm}{/*}\PY{c+cm}{s}\PY{c+cm}{e}\PY{c+cm}{\PYZus{}}\PY{c+cm}{r}\PY{c+cm}{e}\PY{c+cm}{s}\PY{c+cm}{t}\PY{c+cm}{r}\PY{c+cm}{i}\PY{c+cm}{c}\PY{c+cm}{t}\PY{c+cm}{e}\PY{c+cm}{d}\PY{c+cm}{\PYZus{}}\PY{c+cm}{R}\PY{c+cm}{A}\PY{c+cm}{*/}
         \PY{k}{preserve}
         \PY{k}{svmat} distout\PYZus{}restricted\PYZus{}RA
         \PY{k}{tabstat} distout\PYZus{}restricted\PYZus{}RA, stat(sd)
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
    variable |        sd
-------------+----------
distout\_re\textasciitilde{}1 |  4.139767
------------------------
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}23}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{s}\PY{c+cm}{e}\PY{c+cm}{\PYZus{}}\PY{c+cm}{c}\PY{c+cm}{o}\PY{c+cm}{v}\PY{c+cm}{\PYZus{}}\PY{c+cm}{r}\PY{c+cm}{e}\PY{c+cm}{s}\PY{c+cm}{t}\PY{c+cm}{r}\PY{c+cm}{i}\PY{c+cm}{c}\PY{c+cm}{t}\PY{c+cm}{e}\PY{c+cm}{d}\PY{c+cm}{\PYZus{}}\PY{c+cm}{R}\PY{c+cm}{A}
         
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{c}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{c}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{i}\PY{c+c1}{c}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{d}\PY{c+c1}{\PYZus{}}\PY{c+c1}{R}\PY{c+c1}{A}
         \PY{k}{di} \PY{l+s}{\PYZdq{}}\PY{l+s}{A}\PY{l+s}{T}\PY{l+s}{E}\PY{l+s}{ }\PY{l+s}{C}\PY{l+s}{o}\PY{l+s}{n}\PY{l+s}{t}\PY{l+s}{r}\PY{l+s}{o}\PY{l+s}{l}\PY{l+s}{l}\PY{l+s}{i}\PY{l+s}{n}\PY{l+s}{g}\PY{l+s}{ }\PY{l+s}{C}\PY{l+s}{o}\PY{l+s}{v}\PY{l+s}{a}\PY{l+s}{r}\PY{l+s}{i}\PY{l+s}{a}\PY{l+s}{n}\PY{l+s}{c}\PY{l+s}{e}\PY{l+s}{(}\PY{l+s}{R}\PY{l+s}{e}\PY{l+s}{s}\PY{l+s}{t}\PY{l+s}{r}\PY{l+s}{i}\PY{l+s}{c}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{d}\PY{l+s}{ }\PY{l+s}{A}\PY{l+s}{s}\PY{l+s}{s}\PY{l+s}{i}\PY{l+s}{g}\PY{l+s}{n}\PY{l+s}{m}\PY{l+s}{e}\PY{l+s}{n}\PY{l+s}{t}\PY{l+s}{)}\PY{l+s}{=}
         \PY{l+s}{ }\PY{l+s}{\PYZdq{}} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}cov\PYZus{}restricted\PYZus{}RA}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
ATE Controlling Covariance(Restricted Assignment)= 5.3186105
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}24}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{R}\PY{c+c1}{I}\PY{c+c1}{ }\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{e}\PY{c+c1}{r}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{h}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{n}\PY{c+c1}{u}\PY{c+c1}{l}\PY{c+c1}{l}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{=}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{\PYZus{}}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{v}\PY{c+c1}{\PYZus{}}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{i}\PY{c+c1}{c}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{d}\PY{c+c1}{\PYZus{}}\PY{c+c1}{R}\PY{c+c1}{A}
         
         \PY{k}{cap}\PY{k}{ drop} Y0\PYZus{}sim Y1\PYZus{}sim Y\PYZus{}sim
         \PY{k}{qui}\PY{k}{ gen} Y0\PYZus{}sim = Y
         \PY{k}{qui}\PY{k}{ gen} Y1\PYZus{}sim = Y
         \PY{k}{qui}\PY{k}{ gen} Y\PYZus{}sim = .
         \PY{k}{qui}\PY{k}{ replace} Y0\PYZus{}sim = Y \PY{o}{\PYZhy{}} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}cov\PYZus{}restricted\PYZus{}RA}\PY{k}{ if} D\PY{o}{==}\PY{l+m}{1}
         \PY{k}{qui}\PY{k}{ replace} Y1\PYZus{}sim = Y \PY{o}{+} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{ate\PYZus{}cov\PYZus{}restricted\PYZus{}RA}\PY{k}{ if} D\PY{o}{==}\PY{l+m}{0}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}25}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{c}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{p}\PY{c+c1}{a}\PY{c+c1}{c}\PY{c+c1}{e}
         \PY{k}{drop} \PYZus{}\PYZus{}00\PY{o}{*}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}26}]:} \PY{k}{cap}\PY{k}{ matrix}\PY{k}{ drop} distout\PYZus{}cov\PYZus{}restricted\PYZus{}RA 
         \PY{k}{matrix} distout\PYZus{}cov\PYZus{}restricted\PYZus{}RA=\PY{n+nf}{J}(\PY{l+m}{10000}, \PY{l+m}{1}, .)
                
         \PY{k}{qui}\PY{k}{ forvalues} i = \PY{l+m}{1}\PY{o}{/}\PY{l+m}{10000} \PYZob{}
         \PY{k}{	replace} Y\PYZus{}sim = Y0\PYZus{}sim\PY{o}{*}(\PY{l+m}{1}\PY{o}{\PYZhy{}}z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}) \PY{o}{+} Y1\PYZus{}sim\PY{o}{*}(z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}})
         \PY{k}{	tempvar} weight\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}
         \PY{k}{	gen} \PY{n+nv}{`}\PY{n+nv}{w}\PY{n+nv}{e}\PY{n+nv}{i}\PY{n+nv}{g}\PY{n+nv}{h}\PY{n+nv}{t}\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}\PY{n+nv}{\PYZsq{}} = (\PY{l+m}{1}\PY{o}{/}probs)\PY{o}{*}z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} \PY{o}{+}(\PY{l+m}{1}\PY{o}{/}(\PY{l+m}{1}\PY{o}{\PYZhy{}}probs))\PY{o}{*}(\PY{l+m}{1}\PY{o}{\PYZhy{}}z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}})
         \PY{k}{	qui}\PY{k}{ reg} Y\PYZus{}sim x z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} [pw=\PY{n+nv}{`}\PY{n+nv}{w}\PY{n+nv}{e}\PY{n+nv}{i}\PY{n+nv}{g}\PY{n+nv}{h}\PY{n+nv}{t}\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}\PY{n+nv}{\PYZsq{}}]	
         \PY{k}{	matrix} distout\PYZus{}cov\PYZus{}restricted\PYZus{}RA[\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}, \PY{l+m}{1}] = \PYZus{}b[z\PY{n+nv}{`}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}]
         
         \PYZcb{}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}27}]:} \PY{c+cm}{/*}\PY{c+cm}{s}\PY{c+cm}{e}\PY{c+cm}{\PYZus{}}\PY{c+cm}{r}\PY{c+cm}{e}\PY{c+cm}{s}\PY{c+cm}{t}\PY{c+cm}{r}\PY{c+cm}{i}\PY{c+cm}{c}\PY{c+cm}{t}\PY{c+cm}{e}\PY{c+cm}{d}\PY{c+cm}{\PYZus{}}\PY{c+cm}{R}\PY{c+cm}{A}\PY{c+cm}{*/}
         \PY{k}{preserve}
         \PY{k}{svmat} distout\PYZus{}cov\PYZus{}restricted\PYZus{}RA 
         \PY{k}{tabstat} distout\PYZus{}cov\PYZus{}restricted\PYZus{}RA, stat(sd)
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
    variable |        sd
-------------+----------
distout\_co\textasciitilde{}1 |  1.592966
------------------------
    \end{Verbatim}
\end{kframe}
\end{knitrout}

\begin{table}[H]
\centering
\caption{Summary of Estimated Standard Errors} 
\begin{tabular}{rrr}
  \hline
 & Without Covariates & With Covariates \\ 
  \hline
Complete Random Assignment & 4.674 & 1.578 \\ 
  Restricted Random Assignment & 4.140 & 1.593 \\ 
   \hline
\end{tabular}
\end{table}


Without covariates and assuming complete randomization, we obtain a standard error of 4.674. Under restricted randomization, the standard error declines to 4.140.  Including a covariate and assuming complete randomization, we obtain a standard error of 1.578.  Under restricted randomization, the standard error remains essentially unchanged at 1.593. Restricted randomization is akin to blocking, in that it rules out random allocations that result in imbalance; however, its advantages in terms of precision are limited when the researcher controls for a strongly prognostic covariate, which achieves most of the precision gains associated with blocking. 

\end{enumerate}

\section*{Question 6}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}






\end{verbatim}
\end{kframe}
\end{knitrout}


\section*{Question 7}
Researchers may be concerned about using block randomization when they are unsure whether the variable used to form the blocks actually predicts the outcome. Consider the case in which blocks are formed randomly -- in other words, the variable used to form the blocks has no prognostic value whatsoever. Below is a schedule of potential outcomes for four observations. [10pts]

% Table generated by Excel2LaTeX from sheet 'Sheet1'
\begin{table}[H]
  \centering
  \caption{Question 7 Table}
    \begin{tabular}{ccc}
    \toprule
    Subject & Y(0)  & Y(1) \\
    \midrule
    A     & 1     & 2 \\
    B     & 0     & 3 \\
    C     & 2     & 2 \\
    D     & 5     & 5 \\
    \bottomrule
    \end{tabular}%
  \label{tab:addlabel}%
\end{table}%

\begin{enumerate}[a)]
\item Suppose you were to use complete random assignment such that $m=2$ units are assigned to treatment.  What is the sampling variance of the difference-in-means estimator across all six possible random assignments?

% Table generated by Excel2LaTeX from sheet 'Sheet1'
\begin{table}[htbp]
  \centering
  \caption{Question 7a table}
    \begin{tabular}{rrrr}
    \toprule
     Treated Units     &  $\bar{Y(1)}$ &  $\bar{Y(0)}$ &  $\widehat{ATE}$ \\
    \midrule
    A and B & 2.5   & 3.5   & -1 \\
    A and C & 2     & 2.5   & -0.5 \\
    A and D & 3.5   & 1     & 2.5 \\
    B and C & 2.5   & 3     & -0.5 \\
    B and D & 4     & 1.5   & 2.5 \\
    C and D & 3.5     & 0.5   & 3 \\
    \bottomrule
    \end{tabular}%
  \label{tab:addlabel}%
\end{table}%

The average estimated ATE is 1.0, which is the true ATE. The variance of the estimated ATEs over all 6 possible randomizations is 2.833.

\item Suppose you were to form blocks by randomly pairing the observations. Within each pair, you randomly allocate one subject to treatment and the other to control so that $m=2$ units are assigned to treatment.There are three possible blocking schemes; for each blocking scheme, there are four possible random assignments.  What is the sampling variance of the difference-in-means estimator across all twelve possible random assignments?

% Table generated by Excel2LaTeX from sheet 'Sheet1'
\begin{table}[H]
  \centering
  \caption{Question 7b table}
    \begin{tabular}{rrrrr}
    \toprule
          & Treated Units     &  $\bar{Y(1)}$ &  $\bar{Y(0)}$ &  $\widehat{ATE}$ \\
    \midrule
    \multicolumn{1}{c}{\multirow{4}[0]{*}{AB and CD blocked}} & A,C   & 2     & 2.5   & -0.5 \\
    \multicolumn{1}{c}{} & A,D   & 3.5   & 1     & 2.5 \\
    \multicolumn{1}{c}{} & B,D   & 4     & 1.5   & 2.5 \\
    \multicolumn{1}{c}{} & B,C   & 2.5   & 3     & -0.5 \\
          &       &       &       &  \\
    \multicolumn{1}{c}{\multirow{4}[0]{*}{AC and BD blocked}} & A,B   & 2.5   & 3.5   & -1 \\
    \multicolumn{1}{c}{} & A,D   & 3.5   & 1     & 2.5 \\
    \multicolumn{1}{c}{} & C,B   & 2.5   & 3     & -0.5 \\
    \multicolumn{1}{c}{} & C,D   & 3.5   & 0.5   & 3 \\
          &       &       &       &  \\
    \multicolumn{1}{c}{\multirow{4}[0]{*}{AD and BC blocked}} & A,B   & 2.5   & 3.5   & -1 \\
    \multicolumn{1}{c}{} & A,C   & 2     & 2.5   & -0.5 \\
    \multicolumn{1}{c}{} & D,B   & 4     & 1.5   & 2.5 \\
    \multicolumn{1}{c}{} & D,C   & 3.5   & 0.5   & 3 \\
    \bottomrule
    \end{tabular}%
  \label{tab:addlabel}%
\end{table}%

Across the 12 possible random assignments, the variance of the estimated ATE is again 2.833.  Notice that every estimate in the previous table appears in this table twice.

\item From this example, what do you infer about the risks of blocking on a non-prognostic covariate?\\
Answer:\\
There is no risk of increasing variance with a useless blocking variable; at worst, the variable will be random noise, in which case the sampling variance will be the same as a design without blocking.
\end{enumerate}


\section*{Question 8}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}






\end{verbatim}
\end{kframe}
\end{knitrout}


\section*{Question 9}
Gerber and Green conducted a mobilization experiment in which calls from a large commercial phone bank urged voters in Iowa and Michigan to vote in the November 2002 election.\footnote{Gerber and Green 2005.} The randomization was conducted within four blocks: uncompetitive congressional districts in Iowa, competitive congressional districts in Iowa, uncompetitive congressional districts in Michigan, and competitive congressional districts in Michigan. Table 4.3 presents results only for one-voter households in order to sidestep the complications of cluster assignment. [10pts]



\begin{enumerate}[a)]
\item Within each of the four blocks, what was the apparent effect of being called by a phone bank on voter turnout?  \\
Answer:\\
From the ``Estimated ATE'' Row: Block 1: .0096, Block 2: -.0078, Block 3: -.0136, Block 4: .0083.  Substantively, these results suggest that calls encouraging voter turnout had effects ranging from -1.4 percentage points to +1.0 percentage point.
\item When all of the subjects in this experiment are combined (see the rightmost column of the table), turnout seems substantially higher in the treatment group than the control group.  Explain why this comparison gives a biased estimate of the ATE.\\
Answer:\\
This estimator is biased because individuals in each stratum had different propensities to enter into treatment. The uncompetitive Michigan block has the lowest rate of treatment and also has the lowest rate of voting in the control group. Overall, blocks with higher rates of treatment tend to have higher rates of voting in the control group, which accounts for the upward bias.
\item Using the weighted estimator described in Chapter 3, show the calculations used to generate an unbiased estimate of the overall ATE. 
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}1}]:} \PY{k}{clear}
        \PY{k}{input} ests shareoftotalN
        .\PY{l+m}{00964} .\PY{l+m}{049487}
        \PY{o}{\PYZhy{}}.\PY{l+m}{007829} .\PY{l+m}{1520981}
        \PY{o}{\PYZhy{}}.\PY{l+m}{01362} .\PY{l+m}{626616}
        .\PY{l+m}{008271} .\PY{l+m}{171799}
        end
        
        \PY{k}{qui}\PY{k}{ gen} overall\PYZus{}ate = ests\PY{o}{*}shareoftotalN
        \PY{k}{total}(overall\PYZus{}ate)
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
        ests  shareof\textasciitilde{}N

Total estimation                  Number of obs   =          4

--------------------------------------------------------------
             |      Total   Std. Err.     [95\% Conf. Interval]
-------------+------------------------------------------------
 overall\_ate |  -.0078273   .0090322     -.0365719    .0209173
--------------------------------------------------------------

    \end{Verbatim}
\end{kframe}
\end{knitrout}

\item When analyzing block randomized experiments, researchers frequently use regression to estimate the ATE by regressing the outcome on the treatment and indicator variables for each of the blocks (omitting one block if the regression includes an intercept.)  This regression estimator places extra weight on blocks that allocate approximately half of the subjects to the treatment condition (i.e., $P_j  = 0.5$) because these blocks tend to estimate the within-block ATE with less sampling variability. Compare the four OLS weights to the weights $W_j$ used in part (c).\\
Answer:\\
The weights used in part (c) are based on the share of the subject pool that is in each block.  This weighting scheme places a great deal of weight on the relatively large Michigan block. By contrast, the OLS weights are a blend of the number of subjects in each block and each block's balance between treatment and control allocations. Because the blocks do not differ very much in terms of their allocation rates, the OLS weights tend to be similar across blocks.
\item Regression provides an easy way to calculate the weighted estimate of the ATE in part (c) above. For each treatment subject $i$, compute the proportion of subjects in the same block who were assigned to the treatment group.  For control subjects, compute the proportion of subjects in the same block who were assigned to the control group.  Call this variable $q_i$.  Regress outcomes on treatment, weighting each observation by $1/q_i$, and show that this type of weighted regression produces the same estimate as weighting the estimated ATEs for each block.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}2}]:} \PY{k}{clear}
        \PY{k}{qui} import delim .\PY{o}{/}data\PY{o}{/}chapter04\PY{o}{/}Gerber\PYZus{}Green\PYZus{}AAAPSS\PYZus{}2005,\PY{k}{ clear}
        \PY{k}{qui}\PY{k}{ bysort} strata:\PY{k}{ egen} blockpr =\PY{k}{ mean}(treat2)
        \PY{k}{qui}\PY{k}{ gen}\PY{k}{ q} = blockpr\PY{o}{*}treat2 \PY{o}{+} (\PY{l+m}{1}\PY{o}{\PYZhy{}}blockpr)\PY{o}{*}(\PY{l+m}{1}\PY{o}{\PYZhy{}}treat2)
        \PY{k}{regress} vote02 treat2 [aw=\PY{l+m}{1}\PY{o}{/}q]
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
(sum of wgt is   1.8814e+06)

      Source |       SS           df       MS      Number of obs   =   940,715
-------------+----------------------------------   F(1, 940713)    =     57.98
       Model |  14.4110635         1  14.4110635   Prob > F        =    0.0000
    Residual |  233826.144   940,713  .248562679   R-squared       =    0.0001
-------------+----------------------------------   Adj R-squared   =    0.0001
       Total |  233840.555   940,714  .248577734   Root MSE        =    .49856

------------------------------------------------------------------------------
      vote02 |      Coef.   Std. Err.      t    P>|t|     [95\% Conf. Interval]
-------------+----------------------------------------------------------------
      treat2 |   -.007828   .0010281    -7.61   0.000    -.0098429    -.005813
       \_cons |   .4661975   .0007269   641.31   0.000     .4647727    .4676223
------------------------------------------------------------------------------

    \end{Verbatim}
\end{kframe}
\end{knitrout}

The coefficient on the treatment indicator is \ensuremath{-0.0078}, which is the same as was found in part c.

\end{enumerate}


\section*{Question 10}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}






\end{verbatim}
\end{kframe}
\end{knitrout}












\end{document}

