% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PROBLEM SET LATEX TEMPLATE FILE
% DEFINE DOCUMENT STYLE, LOAD PACKAGES
\documentclass[11pt,notitlepage]{article}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}    % ADD COMMENTS USING A PERCENT SIGN
\usepackage{amsfonts}
\usepackage{amsthm}
\usepackage{amsmath, booktabs}
\usepackage{mathtools}
\usepackage{amssymb}
\usepackage{subfig}
\usepackage{setspace}
\usepackage{fullpage}
\usepackage{verbatim}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{longtable}
\usepackage{multicol}
\usepackage{multirow}
\setlength{\parindent}{0in}  	% uncomment to remove indent at start of paragraphs
\usepackage{pdflscape}
\usepackage[english]{babel}
\usepackage[pdftex]{hyperref}
\usepackage{natbib}
\usepackage{caption}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{graphics}
\usepackage{multirow}
\usepackage{graphics}
\usepackage{hyperref}
\usepackage{longtable}
\usepackage{latexsym}
\usepackage{rotating}
\usepackage{setspace}
\usepackage{layouts} 
\usepackage[titletoc]{appendix}
\DeclareGraphicsExtensions{.pdf,.jpg,.png}
\usepackage[margin=1in]{geometry}
\usepackage{enumerate}
\usepackage{float}

\newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{C}[1]{>{\centering\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{R}[1]{>{\raggedleft\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}

\usepackage[T1]{fontenc}				

\usepackage{xcolor}
\usepackage[printwatermark]{xwatermark}
\newwatermark[allpages,color=black!50,angle=45,scale=1,xpos=0,ypos=0]{DO NOT DISTRIBUTE}
\input{pygments.tex}



\title{Field Experiments: Design, Analysis and Interpretation \\
Solutions for Chapter 8 Exercises}
\author{Alan S. Gerber and Donald P. Green\footnote{Solutions prepared by Peter M. Aronow and revised by Alexander Coppock}}
\date{\vspace{-5ex}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

\maketitle

\section*{Question 1}
Important concepts:
\begin{enumerate}[a)]
\item Interpret the expression $Y_i(\mathbf{d}) = Y_i(d)$ and explain how it conveys the non-interference assumption.\\
Answer:\\
The expression $Y_i(d)$ refers to the potential outcome that would be expressed based on the input $d$, which refers to the treatment that subject $i$ receives.  By contrast, $Y_i(\mathbf{d})$ refers to the potential outcome that subject $i$ would express based on the assignments that all of the subjects receive. The equality means that the only input that matters is the treatment that subject $i$ receives. 

\item Why are experiments that involve possible spatial spillover effects (such as the example described in section 8.4) said to involve ``implicit'' clustered assignment?\\
Answer:\\
Because certain units are so closely spaced that if a subject receives spillovers from one of the units, it must receive spillovers from all of the units. In that sense, spillovers are assigned as clusters.

\item In what ways might a within-subjects design violate the non-interference assumption?\\
Answer:\\
In a within-subjects design, the unit of observation is the time period. Non-interference presupposes that each unit's potential outcomes are solely a function of the treatments administered in that period. Possible violations include the following: subjects in one period are affected by the treatments that they may have received in a previous period; subjects in one period may be affected because they anticipate treatments that will be administered in a subsequent period.  

\item What are the attractive properties of a waitlist (or stepped-wedge) design?\\
Answer:\\
If the assumptions for unbiased inference are met, this within-subjects design may provide precise estimates of causal effects even when the number of subjects is limited. In terms of implementation, it may be easier to gain the cooperation of subjects or groups administering the treatment that might otherwise object to the use of a control group because everyone in the study eventually receives the treatment.
\end{enumerate}

\section*{Question 2}
National surveys indicate that college roommates tend to have correlated weights. The more one roommate weighs at the end of the freshman year, the more the other freshman roommate weighs. On the other hand, researchers studying housing arrangements in which roommates are randomly paired together find no correlation between two roommates' weights at the end of their freshman year. Explain how these two facts can be reconciled.\\
Answer:\\
A correlation describes the relationship between roommates' weights. A correlation might arise even if subjects have no effect on one another; for example, if subjects from similar regional or ethnic backgrounds tend to room together, one might observe a correlation. Random pairing of roommates means that, in expectation, there would be no correlation between their weights unless they either affected one another's weights or were both affected by similar environmental factors.

\section*{Question 3}
Sometimes researchers are reluctant to randomly assign individual students in elementary classrooms because they are concerned that treatments administered to some students are likely to spill over to untreated students in the same classroom. In an attempt to get around possible violations of the non-interference assumption, they assign classrooms as clusters to treatment and control, and administer the treatment to all students in a classroom.
\begin{enumerate}[a)]
\item State the non-interference assumption as it applies to the proposed clustered design. \\
Answer:\\
The non-interference assumption depends on the estimand. If the aim is to estimate the causal effect of the intervention on individual students, the non-interference assumption is the same as usual, namely, that each student's potential outcomes are affected only by the treatment administered to that subject. If one is concerned about transmission of treatments between students in the same classroom, that concern would still apply to a clustered design, since potential outcomes may be affected by the treatments that other subjects in the same classroom receive. On the other hand, if one is interested in classroom-level treatment effects (i.e., the difference between a 100\% treated classroom and a 0\% treated classroom), this design sidesteps concerns about within-classroom interference because they are built into the definition of the estimand. In the latter case, the relevant non-interference assumption holds that classroom outcomes are unaffected by the treatment status of other classrooms (e.g., other classrooms in the same school or grade).
\item What causal estimand does the clustered design identify? Does this causal estimand include or exclude spillovers within classrooms?\\
Answer:\\
The causal estimand identified by the clustered design is the average effect of a classroom being 100\% treated versus 0\% treated. This includes within-classroom spillovers at the individual level, but assumes that across-classroom spillovers do not occur.
\end{enumerate}

\section*{Question 4}
Recall from Chapter 3 (exercise 9) the field experiment conducted by Camerer in which he selected pairs of similar horses running in the same race and randomly placed large wagers on one of them to see if his bets affected the amount of money that other bettors placed on both horses.
\begin{enumerate}[a)]
\item Define the potential outcomes in Camerer's study. What non-interference assumption is invoked? \\
Answer:\\
Two definitions for potential outcomes are possible.

The outcome variable in this study was defined as the change in total bets that occur between the pre-intervention period and the post-intervention period.  Presumably, the original study assumed that potential outcomes $Y_i(D_i)$ reflect only the treatment assignment of horse $i$, not the treatment or non-treatment of the other horse in the experimental pair.

Nevertheless, one could define four potential outcomes for each horse: $Y_i(D_i =1, D_j =1)$, $Y_i(D_i =1, D_j =0)$, $Y_i(D_i =0, D_j =1)$, and $Y_i(D_i =0, D_j =0)$, which correspond to the the change in bets for horse $i$ depending on whether $i$, $j$, both, or neither are treated with experimental bets.  Because of the matched pair randomization, horses only ever revealed the second or third of these potential outcomes.

\item What is the causal parameter that this study identifies? \\
Answer:\\
Depending on which non-interference assumption is made, the same difference-in-means estimate refers either to the average difference between $Y_i(D_i = 1)$ and $Y_i(D_i = 0)$ or the average difference between $Y_i(D_i =1, D_j =0)$ and $Y_i(D_i =0, D_j =1)$. Stated plainly, the first is the average effect of treatment on the change in bets.  The second is the average effect of being the treated horse in a pair in which one horse receives the experimental bets.

The treatment effect for a given horse is assumed to be $Y_i(1)-Y_i(0)$, where $Y_i(0)$ is the untreated potential outcome that would be revealed regardless of whether neither horse were treated or only the other paired horse were treated.  In other words, the bets that flow to horse $i$ have nothing to do with whether the other paired horse receives the experimental wager.
\end{enumerate}

\section*{Question 5}
In their study of spillover effects, Sinclair, McConnell, and Green sent mailings to ran-domly selected households encouraging them to vote in an upcoming special election.\footnote{Sinclair, McConnell, and Green 2010.} The mailings used a form of ``social pressure,'' disclosing whether the targeted individual had voted in previous elections. Because this type of mail had proven to increase turnout by approximately 4-5 percentage points in previous experiments, Sinclair, McConnell, and Green used it to study whether treatment effects are transmitted across households. Employing a multi-level design, they randomly assigned all, half, or none of the members of each nine-digit zip code to receive mail. For purposes of this example, we focus only on households with one registered voter. The outcome variable is voter turnout as measured by the registrar of voters. The results are as follows. Among registered voters in untreated zip codes, 1,021 of 6,217 cast ballots. Among untreated voters in zip codes where half of the households received mail, 526 of 3,316 registered voters cast ballots. Among treated voters in zip codes where half of the households received mail, 620 of 2,949 voted. Finally, among treated voters in zip codes where every household received mail, turnout was 1,316 of 6,377.
\begin{enumerate}[a)]
\item Using potential outcomes, define the treatment effect of receiving mail addressed to subject $i$.\\
Answer:\\
The definition of personally receiving mail could be defined in three ways (given our focus on one-voter households). It could be (a) the effect of mail on those whose zip code neighbors receive no mail, (b) the effect of mail on those for whom half of the neighboring households in the zip code receive mail, or (c) the effect of mail on those whose zip code neighbors all receive mail. Given the design of this study, only (b) can be estimated empirically because no one receives mail in an untreated zip code, and everyone receives mail in a 100\% treated zip code.

\item Define the ``spillover'' treatment effect of being in a zip code where varying fractions of households are treated.\\
Answer:\\
Holding constant one's own treatment status, one may define three potential outcomes depending on whether none, half, or all of the neighboring households are treated.  When defining the ATE of spillover, one may compare half to none, full to half, or full to none.
\item Propose an estimator for estimating the firsthand and secondhand treatment effects. Show that the estimator is unbiased, explaining the assumptions required to reach this conclusion. \\
Answer:\\
The firsthand effects can be estimated only for those in half-treated zip codes by comparing average outcomes among treated and untreated subjects. One can assess the spillover effect among subjects who receive no mail themselves but reside in either half-treated or untreated zip codes. Similarly, one can assess the spillover effect among subjects who received mail themselves and reside in either 100\% or 50\% treated zip codes. The three assumptions are random assignment (satisfied by design because direct treatments and rates of treatment among neighbors are randomly assigned), non-interference (satisfied if we believe that potential outcomes are solely a function of firsthand treatment and treatment of others in the same zip code; treatment of those outside the zip code is ignored), and excludability (satisfied if we believe that potential outcomes are affected only by firsthand and second hand receipt of mail and not by other factors that might be correlated with treatment assignment).
\item Based on these data, what do you infer about the magnitude of the mailing's direct and indirect effects?\\

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
   \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}1}]:} \PY{k}{clear} 
        \PY{k}{qui}\PY{k}{ set} obs \PY{l+m}{18859}
        \PY{k}{qui}\PY{k}{ egen} z\PYZus{}ind = fill(\PY{l+m}{0},\PY{l+m}{0})
        \PY{k}{qui}\PY{k}{ replace} z\PYZus{}ind = \PY{l+m}{1}\PY{k}{ in} \PY{l+m}{9534}\PY{o}{/}\PY{l+m}{18859}
        
        \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{s}\PY{c+c1}{c}\PY{c+c1}{ }\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{l}\PY{c+c1}{ }\PY{c+c1}{e}\PY{c+c1}{g}\PY{c+c1}{e}\PY{c+c1}{n}\PY{c+c1}{m}\PY{c+c1}{o}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{(}\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{m}\PY{c+c1}{m}\PY{c+c1}{e}\PY{c+c1}{n}\PY{c+c1}{t}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{o}\PY{c+c1}{ }\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{l}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{h}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{a}\PY{c+c1}{c}\PY{c+c1}{k}\PY{c+c1}{a}\PY{c+c1}{g}\PY{c+c1}{e}\PY{c+c1}{)}
        \PY{k}{qui}\PY{k}{ egen} z\PYZus{}zip =\PY{k}{ repeat}(), values(\PY{l+s}{\PYZdq{}}\PY{l+s}{n}\PY{l+s}{o}\PY{l+s}{n}\PY{l+s}{e}\PY{l+s}{\PYZdq{}})
        \PY{k}{qui}\PY{k}{ replace} z\PYZus{}zip = \PY{l+s}{\PYZdq{}}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{l}\PY{l+s}{f}\PY{l+s}{\PYZdq{}}\PY{k}{ in} \PY{l+m}{6218}\PY{o}{/}\PY{l+m}{12482}
        \PY{k}{qui}\PY{k}{ replace} z\PYZus{}zip = \PY{l+s}{\PYZdq{}}\PY{l+s}{a}\PY{l+s}{l}\PY{l+s}{l}\PY{l+s}{\PYZdq{}}\PY{k}{ in} \PY{l+m}{12483}\PY{o}{/}\PY{l+m}{18859}
        
        \PY{k}{qui}\PY{k}{ egen} Y = fill(\PY{l+m}{1},\PY{l+m}{1})
        \PY{k}{qui}\PY{k}{ replace} Y=\PY{l+m}{0}\PY{k}{ in} \PY{l+m}{1022}\PY{o}{/}\PY{l+m}{6217}
        \PY{k}{qui}\PY{k}{ replace} Y = \PY{l+m}{0}\PY{k}{ in} \PY{l+m}{6744}\PY{o}{/}\PY{l+m}{9533}
        \PY{k}{qui}\PY{k}{ replace} Y=\PY{l+m}{0}\PY{k}{ in} \PY{l+m}{10154}\PY{o}{/}\PY{l+m}{12482}
        \PY{k}{qui}\PY{k}{ replace} Y=\PY{l+m}{0}\PY{k}{ in} \PY{l+m}{13799}\PY{o}{/}\PY{l+m}{18859}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}2}]:} \PY{k}{qui}\PY{k}{ mean} Y\PY{k}{ if} z\PYZus{}ind\PY{o}{==}\PY{l+m}{1} \PY{o}{\PYZam{}} z\PYZus{}zip\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{l}\PY{l+s}{f}\PY{l+s}{\PYZdq{}}
        \PY{k}{scalar} ate\PYZus{}treat\PYZus{}half = \PYZus{}b[Y]
        \PY{k}{qui}\PY{k}{ mean} Y\PY{k}{ if} z\PYZus{}ind\PY{o}{==}\PY{l+m}{0} \PY{o}{\PYZam{}} z\PYZus{}zip\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{l}\PY{l+s}{f}\PY{l+s}{\PYZdq{}}
        \PY{k}{scalar} ate\PYZus{}untreat\PYZus{}half = \PYZus{}b[Y]
        \PY{k}{qui}\PY{k}{ mean} Y\PY{k}{ if} z\PYZus{}ind\PY{o}{==}\PY{l+m}{0} \PY{o}{\PYZam{}} z\PYZus{}zip\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{n}\PY{l+s}{o}\PY{l+s}{n}\PY{l+s}{e}\PY{l+s}{\PYZdq{}}
        \PY{k}{scalar} ate\PYZus{}untreat\PYZus{}none = \PYZus{}b[Y]
        \PY{k}{qui}\PY{k}{ mean} Y\PY{k}{ if} z\PYZus{}ind\PY{o}{==}\PY{l+m}{1} \PY{o}{\PYZam{}} z\PYZus{}zip\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{a}\PY{l+s}{l}\PY{l+s}{l}\PY{l+s}{\PYZdq{}}
        \PY{k}{scalar} ate\PYZus{}treat\PYZus{}all = \PYZus{}b[Y]
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}3}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{.}\PY{c+c1}{f}\PY{c+c1}{r}\PY{c+c1}{i}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{h}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{.}\PY{c+c1}{h}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{f}
        \PY{k}{disp} ate\PYZus{}treat\PYZus{}half \PY{o}{\PYZhy{}} ate\PYZus{}untreat\PYZus{}half
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
.05161591

    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}4}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{.}\PY{c+c1}{s}\PY{c+c1}{e}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{h}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{f}\PY{c+c1}{.}\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{d}
        \PY{k}{disp} ate\PYZus{}untreat\PYZus{}half \PY{o}{\PYZhy{}} ate\PYZus{}untreat\PYZus{}none
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
-.00560227

    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}5}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{.}\PY{c+c1}{s}\PY{c+c1}{e}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{h}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{.}\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{d}
        \PY{k}{disp} ate\PYZus{}treat\PYZus{}all \PY{o}{\PYZhy{}} ate\PYZus{}treat\PYZus{}half
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
-.00387413
    \end{Verbatim}
\end{kframe}
\end{knitrout}

Here, the firsthand effects can be estimated only for those in half-treated zip codes: 620/2949 - 526/3316 = 0.052, or 5.2 percentage points. One can assess spillover effect by way of two different comparisons. In order to assess the effects of spillover among subjects who receive no mail themselves, compare voting rates for those living in 50\% treated zip code to those living in the 0\% treated zip code: 526/3316 - 1021/6217 = -0.006, or negative 0.6 percentage points. In order to assess the effects of spillover among subjects who received mail themselves, compare voting rates for those living in 100\% treated zip codes to those living in 50\% treated zip codes:  1316/6377 - 620/2949 = -0.004, or negative 0.4 percentage points.  Although the estimated firsthand effect is strongly positive, both of the estimated spillover effects are close to zero.
\end{enumerate}

\section*{Question 6}
Using the potential outcomes from the clinic example in Table 8.2, calculate the following estimates.
\begin{enumerate}[a)]
\item Estimate $E[Y_{01} - Y_{00}]$ for the random assignment that places the treatment at location A. \\
Answer:\\
The treated and untreated averages are $\frac{\frac{0}{0.2}}{\frac{1}{0.2}} =0$ and $\frac{\frac{0}{0.4}+\frac{6}{0.6}+\frac{6}{0.8}}{\frac{1}{0.4}+\frac{1}{0.6}+\frac{1}{0.8}} = 3.23$, respectively.  The estimated ATE is $-3.23$.
\item Estimate $E[Y_{10} - Y_{00}]$ for the random assignment that places the treatment at location A, restricting the sample to the set of villages that have a non-zero probability of expressing both of these potential outcomes.\\
Answer:\\
The treated and untreated averages are $\frac{\frac{2}{0.4}}{\frac{1}{0.4}} =2$ and $\frac{\frac{0}{0.4}+\frac{6}{0.6}}{\frac{1}{0.4}+\frac{1}{0.6}} = 2.4$, respectively.  The estimated ATE is $-0.4$.
\item In order to make a more direct comparison between these two treatment effects, estimate $E[Y_{01} - Y_{00}]$, restricting the sample to the same set of villages as in part (b).\\
Answer:\\
The treated and untreated averages are $\frac{\frac{0}{0.2}}{\frac{1}{0.2}} =0$ and $\frac{\frac{0}{0.4}+\frac{6}{0.6}}{\frac{1}{0.4}+\frac{1}{0.6}} = 2.4$, respectively.  The estimated ATE is $-2.4$.
\end{enumerate}

\section*{Question 7}
Lab experiments sometimes pair subjects together and have them play against one another in games where each subject is rewarded financially according to the game's outcome. One such game involves making monetary contributions to a public good (e.g., preserving the environment); the game can be arranged such that each player gains financially if both of them make a contribution, but each player is better off still if they contribute nothing while their partner in the game makes a contribution. The treatment is whether the pair of players is allowed to communicate prior to deciding whether to contribute. Suppose that a lab experimenter recruits four subjects and assigns them randomly as pairs to play this game. The outcome is whether each player makes a contribution: $Y_i$ is 1 if the player contributes and 0 otherwise. Each player has three potential outcomes: $Y_{0i}$ is the outcome if players are prevented from communicating, $Y_{1i}$ is the outcome if a player communicates with another player who is ``persuasive,'' and $Y_{2i}$ is the outcome if a player communicates with another player who is ``unpersuasive.'' The table below shows the schedule of potential outcomes for four players, two of whom are persuasive and two of whom are unpersuasive.

% Table generated by Excel2LaTeX from sheet 'Sheet1'
\begin{table}[H]
  \centering
  \caption{Question 7 Table}
    \begin{tabular}{rrrrr}
    \toprule
    Subject  & Type  & $Y_{0i}$   & $Y_{1i}$   & $Y_{2i}$  \\
    \midrule
    1     & Persuasive  & 0     & 1     & 0 \\
    2     & Persuasive  & 1     & 1     & 0 \\
    3     & Unpersuasive  & 0     & 0     & 0 \\
    4     & Unpersuasive  & 1     & 1     & 1 \\
    \bottomrule
    \end{tabular}%
  \label{tab:addlabel}%
\end{table}%

\begin{enumerate}[a)]
\item Calculate the average treatment effect of $Y_{1i} - Y_{0i}$. Calculate the average treatment effect of $Y_{2i} - Y_{0i}$.\\
Answer:\\
The ATE of talking with a persusaive person is (3/4) - (1/2) = (1/4). The ATE of talking with an unpersusaive person is (1/4) - (1/2) = -(1/4). 
\item How many random pairings are possible with four subjects?\\
Answer:\\
There are $4!/(2!(4-2)!) = 6$ pairings.
\item Suppose that the experimenter ignores the distinction between $Y_{1i}$ and $Y_{2i}$ and considers only two treatment conditions: the control condition prevents communication between pairs of players, and the treatment condition allows communication. Call the observed outcomes in the communication condition $Y^{*}_{1i}$. Across all possible random pairings of subjects, what is the average difference-in-means estimate when the average $Y^{*}_{1i}$ is compared to the average $Y_{0i}$ ? Does this number correspond to either of the two estimands defined in part (a)? Does it correspond to the average of these two estimands? \\
Answer:\\
The average difference-in-means estimate is $\frac{0 - 0.5 -1 + 0 + 0.5 + 0.5}{6} = -\frac{1}{12}$. This does not correspond to any of the estimands defined in part a), nor does it correspond to the average of this estimands.

\item What is the probability that a persuasive subject is treated by communicating with an unpersuasive subject? What is the probability that an unpersuasive subject is treated by communicating with an unpersuasive subject? \\
Answer:\\
Subject 1 has a 1/6 chance of being assigned to communicate with a persuasive subject (subject 2) and has a 1/3 chance of being assigned to communicate with an unpersuasive subject (subjects 3 or 4). The same probabilities apply to Subject 2. Subject 3 has a 1/6 chance of communicating with an unpersuasive subject (subject 4).  The same probabilities apply to Subject 4.
\item Briefly summarize why a violation of the non-interference assumption leads to biased difference-in-means estimates in this example. \\
Answer:\\
One's potential outcomes change depending on how the randomization happened to come out. Bias occurs because the probability of encountering a persuasive or unpersuasive partner is related to potential outcomes.

\item Would bias be eliminated if the experimenter replicated this study (with four subjects) each day and averaged the results over a series of 100 daily studies? \\
Answer:\\
It depends. Replicating small experiments with the same combination of persuasive and unpersuasive subjects simply reproduces the bias described above, because each experiment is subject to the same bias.  On the other hand, if one imagines replicating this study with a random draw of the four subject types (see part G below), no bias results because selecting one subject for treatment does not prevent a subject of the same type from being assigned to control.
\item Would bias be eliminated if the experimenter assembled 400 subjects at the same time (imagine 100 subjects for each of the four potential outcomes profiles in the table) and assigned them to pairs? Hint: Answer the question based on the intuition suggested by part (d). \\
Answer:\\
Bias becomes negligible as the size of a given experiment increases, because in a large experiment the probability of encountering a persuasive partner is nearly the same for both persuasive and unpersuasive subjects.
\end{enumerate}

\section*{Question 8}
Concerns about interference between units sometimes arise in survey experiments. For example, surveys sometimes administer a series of ``vignettes'' involving people with different attributes. A respondent might be told about a low-income person who is randomly described as white or black; after hearing the description, the respondent is asked to rate whether this person deserves public assistance. The respondent is then presented with a vignette about a second person, again randomly described as white or black, and asked about whether this person deserves public assistance. This design creates four experimental groups: (a) two vignettes about blacks, (b) two vignettes about whites, (c) a black vignette followed by a white vignette, and (d) a white vignette followed by a black vignette. Each respondent provides two ratings.

\begin{enumerate}[a)]
\item Propose a model of potential outcomes that reflects the ways that subjects might respond to the treatments and the sequences in which they are presented.\\
Answer:\\
One could model this scenario as a two-period within-subjects experiment. Call the black vignette $D_i=1$ and the white vignette $D_i=0$. Assume that respondents are affected only by the treatments they have received in the past or present; future treatments are irrelevant. For each respondent, the relevant potential outcomes are denoted $Y_{t-1,t}$, where the $t-1$ subscript refers to which (if any) treatment is administered in the preceding time period, $t$ refers to the current time period. This notation allows us to use $Y_{01}$ in period $i$, for example, to refer to that period's potential outcome if a respondent were given the white vignette in the preceding period and the black vignette in the current period. If no question is asked in the preceding period (because the outcome is the response to the first question), denote the outcome as $Y_{*0}$ or $Y_{*1}$.
\item Using your model of potential outcomes, define the ATE or ATEs that a researcher might seek to estimate.\\
Answer:\\
One estimand is the average difference between $Y_{*1}$ and $Y_{*0}$, which is the effect of the vignette on responses to the first question. Another is the average difference between $Y_{01}$ and $Y_{00}$, which is the effect of race on responses to the second question for those who are asked about whites in the first vignette. Similarly, one might consider the average difference between $Y_{11}$ and $Y_{10}$, which is the effect of race on responses to the second question for those who are asked about blacks in the first vignette. 
\item Suggest an identification strategy for estimating this (these) causal estimand(s) using the data from this experiment.\\
Answer:\\
Each of the estimands mentioned in part (b) can be estimated by using the between-subjects part of the design. To estimate $E[Y_{*1}-Y_{*0}]$, compare average responses to the first question among those randomly assigned black or white vignettes.  To estimate $E[Y_{01}-Y_{00}]$, compare average responses to the second question among those randomly assigned black or white vignettes who earlier received a white vignette. To estimate $E[Y_{11}-Y_{10}]$, compare average responses to the second question among those randomly assigned black or white vignettes who earlier received a black vignette. 

\item Suppose a researcher analyzing this experiment estimates the average ``race effect'' by comparing the average evaluation of the white recipient to the average evaluation of the black recipient. Is this a sound approach?\\
Answer:\\
This approach amounts to pooling the respondents' answers to both questions; if there are N respondents, this analysis analyzes 2N observations. If the three race effects defined above differ, this approach will estimate a weighted average of the three estimands, which may be uninterpretable as a causal effect.
\end{enumerate}


\section*{Question 9}
Use data from the hotspots experiment in Table 8.4 (these data are also available at http:// isps.research.yale.edu/FEDAI) and the probabilities that each unit is exposed to immediate or spillover treatments (Table 8.5) to answer the following questions:



\begin{enumerate}[a)]
\item For the subset of 11 hotspot locations that lie outside the range of possible spillovers, calculate $E[Y_{01} - Y_{00}]$, the ATE of immediate police surveillance.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}1}]:} \PY{k}{qui} import delimited \PY{l+s}{\PYZdq{}}\PY{l+s}{.}\PY{l+s}{/}\PY{l+s}{d}\PY{l+s}{a}\PY{l+s}{t}\PY{l+s}{a}\PY{l+s}{/}\PY{l+s}{c}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{p}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{0}\PY{l+s}{8}\PY{l+s}{/}\PY{l+s}{G}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{b}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{G}\PY{l+s}{r}\PY{l+s}{e}\PY{l+s}{e}\PY{l+s}{n}\PY{l+s}{B}\PY{l+s}{o}\PY{l+s}{o}\PY{l+s}{k}\PY{l+s}{\PYZus{}}\PY{l+s}{C}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{p}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{8}\PY{l+s}{\PYZus{}}\PY{l+s}{T}\PY{l+s}{a}\PY{l+s}{b}\PY{l+s}{l}\PY{l+s}{e}\PY{l+s}{\PYZus{}}\PY{l+s}{8}\PY{l+s}{\PYZus{}}\PY{l+s}{4}\PY{l+s}{\PYZus{}}\PY{l+s}{8}\PY{l+s}{\PYZus{}}\PY{l+s}{5}\PY{l+s}{.}\PY{l+s}{c}\PY{l+s}{s}\PY{l+s}{v}\PY{l+s}{\PYZdq{}},\PY{k}{ clear}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}2}]:} \PY{k}{qui}\PY{k}{ mean} y01\PY{k}{ if} prox500\PY{o}{==}\PY{l+m}{0}
        \PY{k}{scalar} mean\PYZus{}y01 = \PYZus{}b[y01]
        \PY{k}{qui}\PY{k}{ mean} y00\PY{k}{ if} prox500\PY{o}{==}\PY{l+m}{0}
        \PY{k}{scalar} mean\PYZus{}y00 = \PYZus{}b[y00]
        \PY{k}{scalar} true\PYZus{}ate = mean\PYZus{}y01\PY{o}{\PYZhy{}}mean\PYZus{}y00
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}3}]:} \PY{k}{disp} true\PYZus{}ate
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
-5
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}4}]:} \PY{k}{qui}\PY{k}{ mean} y\PY{k}{ if} prox500\PY{o}{==}\PY{l+m}{0} \PY{o}{\PYZam{}} assignment \PY{o}{==}\PY{l+m}{1}
        \PY{k}{scalar} mean\PYZus{}y = \PYZus{}b[y]
        \PY{k}{qui}\PY{k}{ mean} y00\PY{k}{ if} prox500\PY{o}{==}\PY{l+m}{0} \PY{o}{\PYZam{}} assignment\PY{o}{==}\PY{l+m}{0}
        \PY{k}{scalar} mean\PYZus{}y00\PYZus{}0 = \PYZus{}b[y00]
        \PY{k}{scalar} ate\PYZus{}hat = mean\PYZus{}y \PY{o}{\PYZhy{}} mean\PYZus{}y00\PYZus{}0
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}5}]:} \PY{k}{disp} ate\PYZus{}hat
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
3.3333333
    \end{Verbatim}
\end{kframe}
\end{knitrout}
The true ATE for the observations that lie outside the range of possibile spillovers is -5. The estimated ATE using the observed random assignment is 3.33.

\item For the remaining 19 hotspot locations that lie within the range of possible spillovers, calculate $E[Y_{01} - Y_{00}]$, $E[Y_{10} - Y_{00}]$, and $E[Y_{11} - Y_{00}]$.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}6}]:} \PY{k}{qui}\PY{k}{ mean} y01\PY{k}{ if} prox500\PY{o}{==}\PY{l+m}{1}
        \PY{k}{scalar} mean\PYZus{}y01 = \PYZus{}b[y01]
        \PY{k}{qui}\PY{k}{ mean} y00\PY{k}{ if} prox500\PY{o}{==}\PY{l+m}{1}
        \PY{k}{scalar} mean\PYZus{}y00 = \PYZus{}b[y00]
        \PY{k}{qui}\PY{k}{ mean} y10\PY{k}{ if} prox500\PY{o}{==}\PY{l+m}{1}
        \PY{k}{scalar} mean\PYZus{}y10 = \PYZus{}b[y10]
        \PY{k}{qui}\PY{k}{ mean} y11\PY{k}{ if} prox500\PY{o}{==}\PY{l+m}{1}
        \PY{k}{scalar} mean\PYZus{}y11 = \PYZus{}b[y11]
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}7}]:} \PY{k}{scalar} true\PYZus{}ate\PYZus{}01 = mean\PYZus{}y01 \PY{o}{\PYZhy{}} mean\PYZus{}y00
        \PY{k}{scalar} true\PYZus{}ate\PYZus{}10 = mean\PYZus{}y10 \PY{o}{\PYZhy{}} mean\PYZus{}y00
        \PY{k}{scalar} true\PYZus{}ate\PYZus{}11 = mean\PYZus{}y11 \PY{o}{\PYZhy{}} mean\PYZus{}y00
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}8}]:} \PY{k}{disp}  true\PYZus{}ate\PYZus{}01
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
-5
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}9}]:} \PY{k}{disp}  true\PYZus{}ate\PYZus{}10
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
5
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}10}]:} \PY{k}{disp}  true\PYZus{}ate\PYZus{}11
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
-7
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}11}]:} \PY{k}{qui}\PY{k}{ gen}\PY{k}{ q} =.
         \PY{k}{qui}\PY{k}{ replace}\PY{k}{ q}=prob10\PY{k}{ if} exposure\PY{o}{==}\PY{l+m}{10}
         \PY{k}{qui}\PY{k}{ replace}\PY{k}{ q}=prob11\PY{k}{ if} exposure\PY{o}{==}\PY{l+m}{11}
         \PY{k}{qui}\PY{k}{ replace}\PY{k}{ q}=prob01\PY{k}{ if} exposure\PY{o}{==}\PY{l+m}{01}
         \PY{k}{qui}\PY{k}{ replace}\PY{k}{ q}=prob00\PY{k}{ if} exposure\PY{o}{==}\PY{l+m}{00}
         \PY{k}{qui}\PY{k}{ gen} weights = \PY{l+m}{1}\PY{o}{/}q
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}12}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{f}\PY{c+c1}{i}\PY{c+c1}{t}\PY{c+c1}{.}\PY{c+c1}{0}\PY{c+c1}{1}
         \PY{k}{qui}\PY{k}{ regress} y i\PY{l+m}{.}exposure\PY{k}{ if} \PY{c+cs}{///}\PY{c+cs}{ }
         prox500\PY{o}{\PYZgt{}}\PY{l+m}{0} \PY{o}{\PYZam{}} (exposure\PY{o}{==}\PY{l+m}{0} | exposure\PY{o}{==}\PY{l+m}{1}) [aweight=weights]
         \PY{k}{estimates} store m1, title(Model \PY{l+m}{1})
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}13}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{f}\PY{c+c1}{i}\PY{c+c1}{t}\PY{c+c1}{.}\PY{c+c1}{1}\PY{c+c1}{0}
         \PY{k}{qui}\PY{k}{ regress} y i\PY{l+m}{.}exposure\PY{k}{ if} \PY{c+cs}{///}
         prox500\PY{o}{\PYZgt{}}\PY{l+m}{0} \PY{o}{\PYZam{}} (exposure\PY{o}{==}\PY{l+m}{0} | exposure\PY{o}{==}\PY{l+m}{10}) [pweight=weights]
         \PY{k}{estimates} store m2, title(Model \PY{l+m}{2})
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}14}]:} \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{f}\PY{c+c1}{i}\PY{c+c1}{t}\PY{c+c1}{.}\PY{c+c1}{1}\PY{c+c1}{1}
         \PY{k}{qui}\PY{k}{ regress} y i\PY{l+m}{.}exposure\PY{k}{ if} \PY{c+cs}{///}
         prox500\PY{o}{\PYZgt{}}\PY{l+m}{0} \PY{o}{\PYZam{}} (exposure\PY{o}{==}\PY{l+m}{0} | exposure\PY{o}{==}\PY{l+m}{11}) [pweight=weights]
         \PY{k}{estimates} store m3, title(Model \PY{l+m}{3})
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}15}]:} estout m1 m2 m3, \PY{c+cs}{///}
         cells(b(star fmt(\PY{l+m}{3}))\PY{k}{ se}(par fmt(\PY{l+m}{3}))) \PY{c+cs}{///}
         legend\PY{k}{ label} varlabels(\PYZus{}cons Constant) \PY{c+cs}{///}
         stats(N r2)
\end{Verbatim}
\end{kframe}
\end{knitrout}

Among observations that lie outside the range of possibile spillovers, the ATE of direct treatment is -5, the ate of indirect treatment is 5, and the ATE of direct and indirect treatment together is -7.


% Table created by stargazer v.5.2 by Marek Hlavac, Harvard University. E-mail: hlavac at fas.harvard.edu
% Date and time: Tue, Apr 10, 2018 - 15:37:27
\begin{table}[!htbp] \centering 
  \caption{Question 9c: Treatment Effect Estimates} 
  \label{} 
\begin{tabular}{@{\extracolsep{2pt}}lccc} 
\\[-1.8ex]\hline \\[-1.8ex] 
\\[-1.8ex] & \multicolumn{3}{c}{Crime Rate} \\ 
\\[-1.8ex] & (1) & (2) & (3)\\ 
\hline \\[-1.8ex] 
 exposure01 & $-$16.033 &  &  \\ 
  & (8.065) &  &  \\ 
  exposure10 &  & $-$0.037 &  \\ 
  &  & (9.074) &  \\ 
  exposure11 &  &  & $-$9.606 \\ 
  &  &  & (7.725) \\ 
  Constant & 62.606 & 62.606 & 62.606 \\ 
  & (5.222) & (4.976) & (4.918) \\ 
 N & 12 & 14 & 11 \\ 
R$^{2}$ & 0.283 & 0.00000 & 0.147 \\ 
\hline \\[-1.8ex] 
\multicolumn{4}{l}{} \\ 
\end{tabular} 
\end{table} 


By comparing weighted averages, with weights equal to the inverse of the probability that an observation is assigned to its observed treatment condition, we obtain estimates for the three ATEs: -16.0, -0.04, -9.6, respectively.

\item Use the data at http://isps.research.yale.edu/FEDAI to estimate the average effect of spillover on nonexperimental units. Note that your estimator must make use of the probability that each unit lies within 500 meters of a treated experimental unit; exclude from your analysis any units that have zero probability of experiencing spillovers.



\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
   \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}16}]:} \PY{k}{clear}
         \PY{k}{qui} import delimited \PY{l+s}{\PYZdq{}}\PY{l+s}{.}\PY{l+s}{/}\PY{l+s}{d}\PY{l+s}{a}\PY{l+s}{t}\PY{l+s}{a}\PY{l+s}{/}\PY{l+s}{c}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{p}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{0}\PY{l+s}{8}\PY{l+s}{/}\PY{l+s}{G}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{b}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{G}\PY{l+s}{r}\PY{l+s}{e}\PY{l+s}{e}\PY{l+s}{n}\PY{l+s}{B}\PY{l+s}{o}\PY{l+s}{o}\PY{l+s}{k}\PY{l+s}{\PYZus{}}\PY{l+s}{C}\PY{l+s}{h}\PY{l+s}{a}\PY{l+s}{p}\PY{l+s}{t}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{8}\PY{l+s}{\PYZus{}}\PY{l+s}{E}\PY{l+s}{x}\PY{l+s}{e}\PY{l+s}{r}\PY{l+s}{c}\PY{l+s}{i}\PY{l+s}{s}\PY{l+s}{e}\PY{l+s}{\PYZus{}}\PY{l+s}{9}\PY{l+s}{c}\PY{l+s}{.}\PY{l+s}{c}\PY{l+s}{s}\PY{l+s}{v}\PY{l+s}{\PYZdq{}},\PY{k}{ clear}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}17}]:} \PY{k}{qui}\PY{k}{ gen}\PY{k}{ q}=.
         \PY{k}{qui}\PY{k}{ replace}\PY{k}{ q}=prob10\PY{k}{ if} exposure\PY{o}{==}\PY{l+m}{10}
         \PY{k}{qui}\PY{k}{ replace}\PY{k}{ q}=prob00\PY{k}{ if} exposure\PY{o}{==}\PY{l+m}{0}
         \PY{k}{qui}\PY{k}{ gen} weights = \PY{l+m}{1}\PY{o}{/}q
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}18}]:} \PY{k}{regress} y i\PY{l+m}{.}exposure\PY{k}{ if} (prob10\PY{o}{\PYZgt{}}\PY{l+m}{0}) \PY{o}{\PYZam{}} (prob10\PY{o}{\PYZlt{}}\PY{l+m}{1}) [pweight=weights]
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
(sum of wgt is   1.5089e+02)

Linear regression                               Number of obs     =         71
                                                F(1, 69)          =      56.95
                                                Prob > F          =     0.0000
                                                R-squared         =     0.5496
                                                Root MSE          =     2.0976

------------------------------------------------------------------------------
             |               Robust
           y |      Coef.   Std. Err.      t    P>|t|     [95\% Conf. Interval]
-------------+----------------------------------------------------------------
 10.exposure |   4.602226   .6098582     7.55   0.000     3.385592     5.81886
       \_cons |   4.285784   .5233643     8.19   0.000     3.241701    5.329867
------------------------------------------------------------------------------

    \end{Verbatim}
\end{kframe}
\end{knitrout}
 
\end{enumerate}

The estimate of the spillover effects of treatment on the non-experimental units is 4.6.


\section*{Question 10}
A doctoral student conducted an experiment in which she randomly varied whether she ran or walked 40 minutes each morning.\footnote{Hough 2010.} In the middle of each afternoon over a period of 26 days, she measured the following outcome variables: (1) her weight (minus a constant, for privacy's sake), (2) her score in a game of Tetris, (3) her mood on a 0-5 scale, with 5 being the most pleasant, (4) her energy level on a 0-5 scale, with 5 being the most energetic, and (5) whether she answered correctly a randomly selected problem from the math section of the GRE. Outcomes are missing for days 13 and 17. The data are listed below.

% 
% % Table generated by Excel2LaTeX from sheet 'Sheet1'
% \begin{table}[H]
%   \centering
%   \caption{Question 10 Table}
%     \begin{tabular}{rrrrrrrr}
%     \toprule
%     Day   & Run   & Weight  & Tetris  & Mood  & Energy  & Appetite  & GRE  \\
%     \midrule
%     1     & 1     & 21    & 11092 & 3     & 3     & 0     & 1 \\
%     2     & 1     & 21    & 14745 & 3     & 1     & 2     & 0 \\
%     3     & 0     & 20    & 11558 & 3     & 3     & 0     & 1 \\
%     4     & 0     & 21    & 11747 & 3     & 1     & 1     & 1 \\
%     5     & 0     & 21    & 14319 & 2     & 3     & 3     & 1 \\
%     6     & 1     & 19    & 7126  & 3     & 2     & 0     & 1 \\
%     7     & 0     & 20    & 16067 & 3     & 4     & 0     & 0 \\
%     8     & 0     & 20    & 3939  & 3     & 2     & 0     & 1 \\
%     9     & 1     & 21    & 28230 & 4     & 2     & 0     & 0 \\
%     10    & 0     & 21    & 17396 & 4     & 4     & 1     & 1 \\
%     11    & 1     & 20    & 36152 & 1     & 4     & 0     & 0 \\
%     12    & 0     & 20    & 16567 & 4     & 4     & 1     & 1 \\
%     13    & 0     & 20    &       &       &       &       &  \\
%     14    & 1     & 18    & 11853 & 4     & 2     & 0     & 1 \\
%     15    & 1     & 18    & 20433 & 4     & 2     & 2     & 1 \\
%     16    & 1     & 18    & 20701 & 3     & 4     & 0     & 0 \\
%     17    & 0     & 20    &       &       &       &       & 1 \\
%     18    & 1     & 19    & 17509 & 3     & 3     & 1     & 1 \\
%     19    & 0     & 21    & 9779  & 3     & 3     & 1     & 0 \\
%     20    & 0     & 22    & 18598 & 3     & 3     & 1     & 1 \\
%     21    & 1     & 20    & 36665 & 2     & 3     & 0     & 1 \\
%     22    & 0     & 21    & 8094  & 4     & 3     & 1     & 1 \\
%     23    & 1     & 19    & 48769 & 2     & 5     & 0     & 0 \\
%     24    & 1     & 20    & 22601 & 4     & 4     & 1     & 1 \\
%     25    & 1     & 19    & 37950 & 4     & 4     & 0     & 1 \\
%     26    & 1     & 20    & 56047 & 4     & 4     & 0     & 1 \\
%     \bottomrule
%     \end{tabular}%
%   \label{tab:addlabel}%
% \end{table}%

\begin{enumerate}[a)]
\item Suppose you were seeking to estimate the average effect of running on her Tetris score. Explain the assumptions needed to identify this causal effect based on this within-subjects design. Are these assumptions plausible in this instance? What special concerns arise due to the fact that the subject was conducting the study, undergoing the treatments, and measuring her own outcomes?\\
Answer:\\
Suppose the effect were defined as $Y_i (1)$ and $Y_i (0)$, where the subscript refers to day. This formulation assumes potential outcomes respond only to the treatments administered that day, with no carryover from days past and no anticipation of treatments to come. The no-anticipation assumption seems reasonable; more questionable is the assumption that Tetris scores respond only to today's treatment, not yesterday's. The potential outcomes above presuppose that the cognitive or physiologic effects of running disappear after a night's sleep.  In order to relax this assumption, one could expand the schedule of potential outcomes to include pairs (or longer sequences) of treatments on successive days. There is a risk of an excludability violation when measuring one's own outcomes; what if the subject tries harder when playing tetris in the wake of a running treatment?

\item Estimate the effect of running on Tetris score. Use randomization inference to test the sharp null hypothesis that running has no immediate or lagged effect on Tetris scores. \\



\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}1}]:} \PY{k}{set}\PY{k}{ more} off
        \PY{k}{clear}
        \PY{k}{macro}\PY{k}{ drop} \PYZus{}all
        \PY{k}{qui} import delim .\PY{o}{/}data\PY{o}{/}chapter08\PY{o}{/}Hough\PYZus{}WorkingPaper\PYZus{}2010,\PY{k}{ clear}
        \PY{k}{set} seed \PY{l+m}{1234567}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}2}]:} \PY{k}{rename} tetris Y
        \PY{k}{rename}\PY{k}{ run} Z
        
        \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{e}\PY{c+c1}{t}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{i}\PY{c+c1}{m}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{v}\PY{c+c1}{a}\PY{c+c1}{r}\PY{c+c1}{i}\PY{c+c1}{a}\PY{c+c1}{b}\PY{c+c1}{l}\PY{c+c1}{e}
        \PY{k}{qui}\PY{k}{ tsset} day
        \PY{k}{qui}\PY{k}{ gen} Zlag =\PY{k}{ l}\PY{l+m}{.}Z
        \PY{k}{qui}\PY{k}{ gen} Ylag =\PY{k}{ l}\PY{l+m}{.}Y
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}3}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{f}\PY{c+cm}{i}\PY{c+cm}{t}\PY{c+cm}{1}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{*/}
        \PY{k}{qui}\PY{k}{ reg} Y Z
        \PY{k}{global} fit1 = \PYZus{}b[Z]
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}4}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{f}\PY{c+cm}{i}\PY{c+cm}{t}\PY{c+cm}{2}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{*/}
        \PY{k}{qui}\PY{k}{ reg} Y Z Zlag
        \PY{k}{global} fit2=\PY{n+nf}{e}(F)
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}5}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{f}\PY{c+cm}{i}\PY{c+cm}{t}\PY{c+cm}{3}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{*/}
        \PY{k}{qui}\PY{k}{ reg} Ylag Z
        \PY{k}{global} fit3=\PYZus{}b[Z]
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}6}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{f}\PY{c+cm}{i}\PY{c+cm}{t}\PY{c+cm}{4}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{*/}
        \PY{k}{qui}\PY{k}{ reg} energy Z
        \PY{k}{global} fit4=\PYZus{}b[Z]
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}7}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{f}\PY{c+cm}{i}\PY{c+cm}{t}\PY{c+cm}{5}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{*/}
        \PY{k}{qui}\PY{k}{ reg} gre Z
        \PY{k}{global} fit5=\PYZus{}b[Z]
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}8}]:} \PY{k}{cap}\PY{k}{ program}\PY{k}{ drop} coeff\PYZus{}Z
        \PY{k}{program} define coeff\PYZus{}Z, rclass
        \PY{k}{	args} Y
        \PY{k}{	tempvar} rannum Zri
        \PY{k}{	gen} \PY{n+nv}{`}\PY{n+nv}{r}\PY{n+nv}{a}\PY{n+nv}{n}\PY{n+nv}{n}\PY{n+nv}{u}\PY{n+nv}{m}\PY{n+nv}{\PYZsq{}} = \PY{n+nf}{uniform}()
        \PY{k}{	egen} \PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{r}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} = cut(\PY{n+nv}{`}\PY{n+nv}{r}\PY{n+nv}{a}\PY{n+nv}{n}\PY{n+nv}{n}\PY{n+nv}{u}\PY{n+nv}{m}\PY{n+nv}{\PYZsq{}}), \PY{n+nf}{group}(\PY{l+m}{2})
        \PY{k}{	qui}\PY{k}{ reg} \PY{n+nv}{`}\PY{n+nv}{Y}\PY{n+nv}{\PYZsq{}} \PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{r}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}
        \PY{k}{	return}\PY{k}{ scalar} coef\PYZus{}Z = \PYZus{}b[\PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{r}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}]
        end
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}9}]:} \PY{k}{cap}\PY{k}{ program}\PY{k}{ drop} F\PYZus{}stat
        \PY{k}{program} define F\PYZus{}stat, rclass
        \PY{k}{	args} Y day
        \PY{k}{	tsset} \PY{n+nv}{`}\PY{n+nv}{d}\PY{n+nv}{a}\PY{n+nv}{y}\PY{n+nv}{\PYZsq{}}
        \PY{k}{	tempvar} rannum Zri
        \PY{k}{	gen} \PY{n+nv}{`}\PY{n+nv}{r}\PY{n+nv}{a}\PY{n+nv}{n}\PY{n+nv}{n}\PY{n+nv}{u}\PY{n+nv}{m}\PY{n+nv}{\PYZsq{}} = \PY{n+nf}{uniform}()
        \PY{k}{	egen} \PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{r}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}} = cut(\PY{n+nv}{`}\PY{n+nv}{r}\PY{n+nv}{a}\PY{n+nv}{n}\PY{n+nv}{n}\PY{n+nv}{u}\PY{n+nv}{m}\PY{n+nv}{\PYZsq{}}), \PY{n+nf}{group}(\PY{l+m}{2})
        \PY{k}{	qui}\PY{k}{ reg} \PY{n+nv}{`}\PY{n+nv}{Y}\PY{n+nv}{\PYZsq{}} \PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{r}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}\PY{k}{ l}.\PY{n+nv}{`}\PY{n+nv}{Z}\PY{n+nv}{r}\PY{n+nv}{i}\PY{n+nv}{\PYZsq{}}
        \PY{k}{	return}\PY{k}{ scalar} fstat =\PY{k}{ e}(F)
        end
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}10}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{ }\PY{c+cm}{d}\PY{c+cm}{i}\PY{c+cm}{s}\PY{c+cm}{t}\PY{c+cm}{1}\PY{c+cm}{ }\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{*/}
         \PY{k}{preserve}	
         \PY{k}{simulate}  coef\PYZus{}Z=\PY{n+nf}{r}(coef\PYZus{}Z), reps(\PY{l+m}{10000}) nodots: coeff\PYZus{}Z Y	
         \PY{k}{qui}\PY{k}{ count}\PY{k}{ if} coef\PYZus{}Z \PY{o}{\PYZgt{}=} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{fit1}
         
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{o}\PY{c+c1}{n}\PY{c+c1}{e}\PY{c+c1}{\PYZhy{}}\PY{c+c1}{t}\PY{c+c1}{a}\PY{c+c1}{i}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{d}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{\PYZhy{}}\PY{c+c1}{v}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{u}\PY{c+c1}{e}\PY{c+c1}{:}\PY{c+c1}{ }\PY{c+c1}{d}\PY{c+c1}{o}\PY{c+c1}{e}\PY{c+c1}{s}\PY{c+c1}{ }\PY{c+c1}{r}\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{n}\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{g}\PY{c+c1}{ }\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{c}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{s}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{T}\PY{c+c1}{e}\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{i}\PY{c+c1}{s}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{s}
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{m}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{(}\PY{c+c1}{d}\PY{c+c1}{i}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{1}\PY{c+c1}{ }\PY{c+c1}{\PYZgt{}}\PY{c+c1}{=}\PY{c+c1}{ }\PY{c+c1}{f}\PY{c+c1}{i}\PY{c+c1}{t}\PY{c+c1}{1}\PY{c+c1}{)}\PY{c+c1}{ }
         \PY{k}{disp} \PY{n+nf}{r}(N)\PY{o}{/}\PYZus{}N
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
.004
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}11}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{ }\PY{c+cm}{d}\PY{c+cm}{i}\PY{c+cm}{s}\PY{c+cm}{t}\PY{c+cm}{2}\PY{c+cm}{ }\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{*/}
         \PY{k}{preserve}	
         \PY{k}{simulate}  fstat=\PY{n+nf}{r}(fstat), reps(\PY{l+m}{10000}) nodots: F\PYZus{}stat Y day
         \PY{k}{qui}\PY{k}{ count}\PY{k}{ if} fstat \PY{o}{\PYZgt{}=} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{fit2}
         
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{o}\PY{c+c1}{n}\PY{c+c1}{e}\PY{c+c1}{\PYZhy{}}\PY{c+c1}{t}\PY{c+c1}{a}\PY{c+c1}{i}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{d}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{\PYZhy{}}\PY{c+c1}{v}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{u}\PY{c+c1}{e}\PY{c+c1}{:}\PY{c+c1}{ }\PY{c+c1}{d}\PY{c+c1}{o}\PY{c+c1}{e}\PY{c+c1}{s}\PY{c+c1}{ }\PY{c+c1}{r}\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{n}\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{g}\PY{c+c1}{ }\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{c}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{s}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{T}\PY{c+c1}{e}\PY{c+c1}{t}\PY{c+c1}{r}\PY{c+c1}{i}\PY{c+c1}{s}\PY{c+c1}{ }\PY{c+c1}{s}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{s}
         \PY{c+cm}{/*}\PY{c+cm}{ }\PY{c+cm}{m}\PY{c+cm}{e}\PY{c+cm}{a}\PY{c+cm}{n}\PY{c+cm}{(}\PY{c+cm}{d}\PY{c+cm}{i}\PY{c+cm}{s}\PY{c+cm}{t}\PY{c+cm}{2}\PY{c+cm}{ }\PY{c+cm}{\PYZgt{}}\PY{c+cm}{=}\PY{c+cm}{ }\PY{c+cm}{f}\PY{c+cm}{i}\PY{c+cm}{t}\PY{c+cm}{2}\PY{c+cm}{)}\PY{c+cm}{ }\PY{c+cm}{*/}
         \PY{k}{disp} \PY{n+nf}{r}(N)\PY{o}{/}\PYZus{}N
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
.0146
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}12}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{ }\PY{c+cm}{d}\PY{c+cm}{i}\PY{c+cm}{s}\PY{c+cm}{t}\PY{c+cm}{3}\PY{c+cm}{ }\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{*/}
         \PY{k}{preserve}	
         \PY{k}{simulate}  coef\PYZus{}Z=\PY{n+nf}{r}(coef\PYZus{}Z), reps(\PY{l+m}{10000}) nodots: coeff\PYZus{}Z Ylag
         \PY{k}{qui}\PY{k}{ count}\PY{k}{ if} \PY{n+nf}{abs}(coef\PYZus{}Z) \PY{o}{\PYZgt{}=} \PY{n+nf}{abs}(\PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{fit3})
         
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{w}\PY{c+c1}{o}\PY{c+c1}{\PYZhy{}}\PY{c+c1}{t}\PY{c+c1}{a}\PY{c+c1}{i}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{d}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{\PYZhy{}}\PY{c+c1}{v}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{u}\PY{c+c1}{e}\PY{c+c1}{:}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{l}\PY{c+c1}{a}\PY{c+c1}{c}\PY{c+c1}{e}\PY{c+c1}{b}\PY{c+c1}{o}\PY{c+c1}{ }\PY{c+c1}{f}\PY{c+c1}{i}\PY{c+c1}{t}
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{m}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{(}\PY{c+c1}{d}\PY{c+c1}{i}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{3}\PY{c+c1}{ }\PY{c+c1}{\PYZgt{}}\PY{c+c1}{=}\PY{c+c1}{ }\PY{c+c1}{f}\PY{c+c1}{i}\PY{c+c1}{t}\PY{c+c1}{3}\PY{c+c1}{)}\PY{c+c1}{ }
         \PY{k}{disp} \PY{n+nf}{r}(N)\PY{o}{/}\PYZus{}N
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
.8879
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}13}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{ }\PY{c+cm}{d}\PY{c+cm}{i}\PY{c+cm}{s}\PY{c+cm}{t}\PY{c+cm}{4}\PY{c+cm}{ }\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{*/}
         \PY{k}{preserve}	
         \PY{k}{simulate}  coef\PYZus{}Z=\PY{n+nf}{r}(coef\PYZus{}Z), reps(\PY{l+m}{10000}) nodots: coeff\PYZus{}Z energy 
         \PY{k}{qui}\PY{k}{ count}\PY{k}{ if} coef\PYZus{}Z \PY{o}{\PYZgt{}=} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{fit4}
         
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{o}\PY{c+c1}{n}\PY{c+c1}{e}\PY{c+c1}{\PYZhy{}}\PY{c+c1}{t}\PY{c+c1}{a}\PY{c+c1}{i}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{d}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{\PYZhy{}}\PY{c+c1}{v}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{u}\PY{c+c1}{e}\PY{c+c1}{:}\PY{c+c1}{ }\PY{c+c1}{d}\PY{c+c1}{o}\PY{c+c1}{e}\PY{c+c1}{s}\PY{c+c1}{ }\PY{c+c1}{r}\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{n}\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{g}\PY{c+c1}{ }\PY{c+c1}{i}\PY{c+c1}{m}\PY{c+c1}{p}\PY{c+c1}{r}\PY{c+c1}{o}\PY{c+c1}{v}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{e}\PY{c+c1}{n}\PY{c+c1}{e}\PY{c+c1}{r}\PY{c+c1}{g}\PY{c+c1}{y}
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{m}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{(}\PY{c+c1}{d}\PY{c+c1}{i}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{4}\PY{c+c1}{ }\PY{c+c1}{\PYZgt{}}\PY{c+c1}{=}\PY{c+c1}{ }\PY{c+c1}{f}\PY{c+c1}{i}\PY{c+c1}{t}\PY{c+c1}{4}\PY{c+c1}{)}
         \PY{k}{disp} \PY{n+nf}{r}(N)\PY{o}{/}\PYZus{}N
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
.5033
    \end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}14}]:} \PY{c+cm}{/*}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{ }\PY{c+cm}{d}\PY{c+cm}{i}\PY{c+cm}{s}\PY{c+cm}{t}\PY{c+cm}{5}\PY{c+cm}{ }\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{\PYZhy{}}\PY{c+cm}{*/}
         \PY{k}{preserve}	
         \PY{k}{simulate}  coef\PYZus{}Z=\PY{n+nf}{r}(coef\PYZus{}Z), reps(\PY{l+m}{10000}) nodots: coeff\PYZus{}Z gre 
         \PY{k}{qui}\PY{k}{ count}\PY{k}{ if} coef\PYZus{}Z \PY{o}{\PYZgt{}=} \PY{n+nv+vg}{\PYZdl{}}\PY{n+nv+vg}{fit5}
         
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{o}\PY{c+c1}{n}\PY{c+c1}{e}\PY{c+c1}{\PYZhy{}}\PY{c+c1}{t}\PY{c+c1}{a}\PY{c+c1}{i}\PY{c+c1}{l}\PY{c+c1}{e}\PY{c+c1}{d}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{\PYZhy{}}\PY{c+c1}{v}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{u}\PY{c+c1}{e}\PY{c+c1}{:}\PY{c+c1}{ }\PY{c+c1}{d}\PY{c+c1}{o}\PY{c+c1}{e}\PY{c+c1}{s}\PY{c+c1}{ }\PY{c+c1}{r}\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{n}\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{g}\PY{c+c1}{ }\PY{c+c1}{i}\PY{c+c1}{m}\PY{c+c1}{p}\PY{c+c1}{r}\PY{c+c1}{o}\PY{c+c1}{v}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{G}\PY{c+c1}{R}\PY{c+c1}{E}
         \PY{c+c1}{//}\PY{c+c1}{ }\PY{c+c1}{m}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{(}\PY{c+c1}{d}\PY{c+c1}{i}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{5}\PY{c+c1}{ }\PY{c+c1}{\PYZgt{}}\PY{c+c1}{=}\PY{c+c1}{ }\PY{c+c1}{f}\PY{c+c1}{i}\PY{c+c1}{t}\PY{c+c1}{5}\PY{c+c1}{)}\PY{c+c1}{ }
         \PY{k}{disp} \PY{n+nf}{r}(N)\PY{o}{/}\PYZus{}N
         \PY{k}{restore}
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
.8137
    \end{Verbatim}
\end{kframe}
\end{knitrout}

Focusing solely on the immediate effect of running that day's tetris scores, we see that on non-running days the average tetris score is 12,806, as compared to 26,419 on running days, for a difference of 13,613. Randomization inference indicates that this observed difference has a one-tailed $p$-value of 0.004. Using the F-statistic to assess the joint significance of immediate and one-period lagged effects, we obtain a $p$-value of 0.0146, again allowing us to reject the null hypothesis of no effect.

\item One way to lend credibility to within-subjects results is to verify the no-anticipation assumption. Use the variable Run to predict the Tetris score \textit{on the preceding day}. Presumably, the true effect is zero. Does randomization inference confirm this prediction? \\
Answer:\\
See code block above for calculations. As expected, the means are similar (18,903 for control and 19,549 for treatment), and the two-tailed $p$-value is 0.8879.

\item If Tetris responds to exercise, one might suppose that energy levels and GRE scores would as well. Are these hypotheses borne out by the data?\\
Answer:\\
No, energy has a difference-in-means of just 0.07 and a $p$-value of 0.5033; and GRE's effect goes (insignificantly, $p$=0.8137) in the wrong direction, with the treatment diminishing the probability of a right answer by 0.175.
\end{enumerate}

\section*{Question 11}
Return to the stepped-wedge advertising example in section 8.6 and the schedule of assigned treatments in Table 8.8.
\begin{enumerate}[a)]
\item Estimate $E[Y_{01}-Y_{00}]$ by restricting your attention to weeks 2 and 3. How does this estimate compare to the estimate of $E[Y_{11} - Y_{00}]$ presented in the text, which is also identified using observations from weeks 2 and 3?

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}1}]:} \PY{k}{clear}
        \PY{k}{qui}\PY{k}{ set} obs \PY{l+m}{16}
        \PY{c+c1}{//}\PY{c+c1}{(}\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{c}\PY{c+c1}{o}\PY{c+c1}{m}\PY{c+c1}{m}\PY{c+c1}{e}\PY{c+c1}{n}\PY{c+c1}{t}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{o}\PY{c+c1}{ }\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{l}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{h}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{p}\PY{c+c1}{a}\PY{c+c1}{c}\PY{c+c1}{k}\PY{c+c1}{a}\PY{c+c1}{g}\PY{c+c1}{e}\PY{c+c1}{)}
        \PY{c+c1}{//}\PY{c+c1}{s}\PY{c+c1}{s}\PY{c+c1}{c}\PY{c+c1}{ }\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{s}\PY{c+c1}{t}\PY{c+c1}{a}\PY{c+c1}{l}\PY{c+c1}{l}\PY{c+c1}{ }\PY{c+c1}{e}\PY{c+c1}{g}\PY{c+c1}{e}\PY{c+c1}{n}\PY{c+c1}{m}\PY{c+c1}{o}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{ }
        \PY{k}{qui}\PY{k}{ egen} week =\PY{k}{ repeat}(), values(\PY{l+s}{\PYZdq{}}\PY{l+s}{2}\PY{l+s}{\PYZdq{}})
        \PY{k}{qui}\PY{k}{ replace} week = \PY{l+s}{\PYZdq{}}\PY{l+s}{3}\PY{l+s}{\PYZdq{}}\PY{k}{ in} \PY{l+m}{9}\PY{o}{/}l
        \PY{k}{qui}\PY{k}{ egen} prob00 = fill(\PY{l+m}{0.5},\PY{l+m}{0.5})
        \PY{k}{qui}\PY{k}{ replace} prob00=\PY{l+m}{0.25}\PY{k}{ in} \PY{l+m}{9}\PY{o}{/}l
        \PY{k}{qui}\PY{k}{ egen} prob01 = fill(\PY{l+m}{0.25},\PY{l+m}{0.25})
        \PY{k}{qui}\PY{k}{ egen} prob11 = fill(\PY{l+m}{0.25},\PY{l+m}{0.25})
        \PY{k}{qui}\PY{k}{ replace} prob11 = \PY{l+m}{0.5}\PY{k}{ in} \PY{l+m}{9}\PY{o}{/}l
\end{Verbatim}


    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}5}]:} \PY{k}{input} int y str2 z
        \PY{l+m}{9} \PY{l+s}{\PYZdq{}}\PY{l+s}{1}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{5} \PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{0}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{2} \PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{3} \PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{0}\PY{l+s}{\PYZdq{}}	
        \PY{l+m}{3} \PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{0}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{8} \PY{l+s}{\PYZdq{}}\PY{l+s}{1}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{3} \PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{0}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{1} \PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{4} \PY{l+s}{\PYZdq{}}\PY{l+s}{1}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{7} \PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{10} \PY{l+s}{\PYZdq{}}\PY{l+s}{1}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{10} \PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{3} \PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{0}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{10} \PY{l+s}{\PYZdq{}}\PY{l+s}{1}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{4} \PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{0}\PY{l+s}{\PYZdq{}}
        \PY{l+m}{3} \PY{l+s}{\PYZdq{}}\PY{l+s}{1}\PY{l+s}{1}\PY{l+s}{\PYZdq{}} end
\end{Verbatim}


    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}6}]:} \PY{k}{gen} prob01z = prob01\PY{k}{ if} z\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{k}{replace} prob01z = prob01\PY{k}{ if} prob01z\PY{o}{==}.
        \PY{c+c1}{//}\PY{c+c1}{d}\PY{c+c1}{i}\PY{c+c1}{f}\PY{c+c1}{f}\PY{c+c1}{e}\PY{c+c1}{r}\PY{c+c1}{e}\PY{c+c1}{n}\PY{c+c1}{c}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{i}\PY{c+c1}{n}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{h}\PY{c+c1}{e}\PY{c+c1}{ }\PY{c+c1}{w}\PY{c+c1}{a}\PY{c+c1}{y}\PY{c+c1}{ }\PY{c+c1}{t}\PY{c+c1}{h}\PY{c+c1}{a}\PY{c+c1}{t}\PY{c+c1}{ }\PY{c+c1}{R}\PY{c+c1}{ }\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{d}\PY{c+c1}{ }\PY{c+c1}{S}\PY{c+c1}{T}\PY{c+c1}{A}\PY{c+c1}{T}\PY{c+c1}{A}\PY{c+c1}{ }\PY{c+c1}{w}\PY{c+c1}{e}\PY{c+c1}{i}\PY{c+c1}{g}\PY{c+c1}{h}\PY{c+c1}{t}\PY{c+c1}{e}\PY{c+c1}{d}\PY{c+c1}{ }\PY{c+c1}{m}\PY{c+c1}{e}\PY{c+c1}{a}\PY{c+c1}{n}\PY{c+c1}{ }\PY{c+c1}{f}\PY{c+c1}{u}\PY{c+c1}{n}\PY{c+c1}{c}\PY{c+c1}{t}\PY{c+c1}{i}\PY{c+c1}{o}\PY{c+c1}{n}\PY{c+c1}{s}
        \PY{k}{gen} y01z = y\PY{k}{ if} z\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{1}\PY{l+s}{\PYZdq{}}
        \PY{k}{egen} mean01 = wtmean(y01z), weight(\PY{l+m}{1}\PY{o}{/}prob01z)
        \PY{k}{gen} prob00z = prob00\PY{k}{ if} z\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{0}\PY{l+s}{\PYZdq{}}
        \PY{k}{replace} prob00z = prob00\PY{k}{ if} prob01z\PY{o}{==}.
        \PY{k}{gen} y00z= y\PY{k}{ if} z\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{0}\PY{l+s}{\PYZdq{}}
        \PY{k}{egen} mean00 = wtmean(y00z), weight(\PY{l+m}{1}\PY{o}{/}prob00z)
        \PY{k}{gen} ate01\PYZus{}00 = mean01 \PY{o}{\PYZhy{}} mean00
        \PY{k}{disp} ate01\PYZus{}00
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
1.5
    \end{Verbatim}

\end{kframe}
\end{knitrout}
The effect of immediate treatment appears to be 1.5, which is weaker than the effect mentioned in the text (4.13), possibly suggesting that the effect of immediate treatment is weaker than the effect of immediate and lagged treatment.

\item Estimate $E[Y_{11} - Y_{00}]$ without imposing the assumption that treatment effects disappear after two weeks by restricting your attention to week 2.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
   \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}7}]:} \PY{k}{gen} prob01z2 = prob01\PY{k}{ if} z\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{1}\PY{l+s}{\PYZdq{}} \PY{o}{\PYZam{}} week\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{2}\PY{l+s}{\PYZdq{}}
        \PY{k}{gen} y11z2 = y\PY{k}{ if} z\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{1}\PY{l+s}{1}\PY{l+s}{\PYZdq{}} \PY{o}{\PYZam{}} week\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{2}\PY{l+s}{\PYZdq{}}
        \PY{k}{replace} prob01z2 = .\PY{l+m}{25}\PY{k}{ if} prob01z2\PY{o}{==}.
        \PY{k}{egen} mean11 = wtmean(y11z2), weight(\PY{l+m}{1}\PY{o}{/}prob01z2)
        \PY{k}{gen} prob00z2 = prob01\PY{k}{ if} z\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{0}\PY{l+s}{\PYZdq{}} \PY{o}{\PYZam{}} week\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{2}\PY{l+s}{\PYZdq{}}
        \PY{k}{replace} prob00z2 = prob01\PY{k}{ if} prob00z2\PY{o}{==}.
        \PY{k}{gen} y00z2 = y\PY{k}{ if} z\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{0}\PY{l+s}{0}\PY{l+s}{\PYZdq{}} \PY{o}{\PYZam{}} week\PY{o}{==}\PY{l+s}{\PYZdq{}}\PY{l+s}{2}\PY{l+s}{\PYZdq{}}
        \PY{k}{drop} mean00
        \PY{k}{egen} mean00 = wtmean(y00z2), weight(\PY{l+m}{1}\PY{o}{/}prob00z2)
        
        \PY{k}{gen} ate11\PYZus{}00 = mean11 \PY{o}{\PYZhy{}} mean00
        \PY{k}{disp} ate11\PYZus{}00
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
5
    \end{Verbatim}
\end{kframe}
\end{knitrout}

Without imposing this assumption and focusing only on week two, the estimated ATE of immediate and lagged treatment is 5.
\end{enumerate}

\end{document}

